Repository Liberty-Landing/Liberty-Station-13, pull requests merged in 2023-06, with the labels that each got.

#415 Bigger Workshop Doors
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Map

#416 Club Manager Alt Titles & Cloak Tweaks
  code/game/jobs/job/service.dm
  code/modules/clothing/accessories/accessory.dm
Labels: Enhancement

#414 help i can hold all these new breakdowns
  code/modules/sanity/breakdowns.dm
Labels: Balance, Content

#417 club worker health fix
  code/game/jobs/job/service.dm
Labels: Balance

#413 Silenced antimatter, made borg UI prettier
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/_onclick/hud/screen_objects/robot_screen_objects.dm
  code/datums/datum_hud.dm
  code/modules/power/antimatter/control.dm
  code/modules/unit_tests/mob_tests.dm
  icons/mob/hud_robot.dmi
Labels: Enhancement, Port, Sprite Work

#426 ShieldsSpriteUpdate
  code/game/objects/items/weapons/shields.dm
  icons/inventory/back/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/weapons.dmi
Labels: Bug-Fix, Sprite Work

#427 PIRS precursor access
  maps/__DeepTunnels/map/_Liberty_Deep_Tunnels.dmm
Labels: Map

#428 Background Stats, Engineer gaming, sprite fixes
  code/datums/setup_option/backgrounds/ancestry/ancestry_human.dm
  code/datums/setup_option/backgrounds/path/path.dm
  code/game/jobs/job/engineering.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/modules/clothing/under/jobs/engineering.dm
  icons/inventory/back/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Bug-Fix, Balance

#433 WOE, WOE INDEED.
  code/datums/topic/admin.dm
Labels: BYOND

#440 More TGS Integration
  code/controllers/configuration.dm
  code/controllers/master.dm
  code/modules/tgs_integration/tgs_procs.dm
  config/example/config.txt
  liberty-station.dme
Labels: BYOND

#439 Union Addings
  code/datums/outfits/jobs/engineering.dm
  code/modules/clothing/under/jobs/engineering.dm
Labels: Balance, Sprite Work

#437 fixes caseless gun, and some turrets
  code/datums/autolathe/guns.dm
  code/game/machinery/tesla_turret.dm
  code/game/objects/items/weapons/circuitboards/machinery/tesla_turret.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/boltgun/contractor.dm
  icons/obj/guns/projectile/contractor.dmi
Labels: Bug-Fix, Sprite Work

#436 card carp meets maker
  code/game/objects/effects/decals/crayon.dm
  modular_liberty/cardgame_2/cardgame_2.dm
  modular_liberty/cardgame_2/cardholder.dm
  modular_liberty/cardgame_2/cardpacks_and_spawner.dm
Labels: Enhancement, Balance

#442 fixes icons for terra
  code/modules/clothing/under/jobs/engineering.dm
  icons/inventory/uniform/icon.dmi
Labels: Bug-Fix

#443 forgotton _role
  config/example/config.txt
Labels: BYOND

#444 belt changes
  code/datums/outfits/jobs/engineering.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
Labels: Bug-Fix, Balance

#448 xenoarch replicator icon fix
  code/modules/research/xenoarchaeology/artifact/artifact_replicator.dm
Labels: Bug-Fix

#447 custodian tweaks again
  code/datums/autolathe/biomatter.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/modules/biomatter_manipulation/bioreactor/bioreactor.dm
  code/modules/biomatter_manipulation/bioreactor/biotank.dm
  code/modules/biomatter_manipulation/bioreactor/console.dm
  code/modules/biomatter_manipulation/bioreactor/loader.dm
  code/modules/biomatter_manipulation/bioreactor/platform.dm
  code/modules/biomatter_manipulation/bioreactor/port.dm
  code/modules/biomatter_manipulation/toxic_biomass.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/group.dm
  code/modules/core_implant/cruciform/rituals/machinery.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/core_implant/cruciform/upgrades.dm
  code/modules/genetics/creatures/wasonce.dm
  code/modules/mob/living/carbon/superior_animal/roach/life.dm
  code/modules/organs/internal/carrion.dm
  code/modules/reagents/reagents/toxins.dm
Labels: Bug-Fix, Balance

#449 small rebalance to rock and hud fix for bot
  code/_onclick/hud/screen_objects/robot_screen_objects.dm
  code/modules/projectiles/projectile/ameridian.dm
Labels: Bug-Fix, Balance

#446 BEGONE check_surrounding_area
  code/__HELPERS/game.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_powers.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/sanity/sanity_mob.dm
  modular_liberty/Borers/borer.dm
Labels: Documentation, Enhancement, Test Merged

#452 No more death whispers
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Bug-Fix

#453 Few more fixes to mob AI activation.
  code/modules/mob/living/living.dm
  code/modules/sanity/sanity_mob.dm
Labels: Bug-Fix

#455 Fixed AI_INACTIVE on mobs versus humans
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/living.dm
Labels: Bug-Fix

#456 Bugfixes and more new content
  code/datums/craft/recipe.dm
  code/datums/craft/recipes/guns.dm
  code/datums/craft/recipes/lodge.dm
  code/datums/craft/recipes/misc.dm
  code/datums/craft/recipes/repairs.dm
  code/datums/craft/recipes/weapon.dm
  code/game/jobs/job/prospector.dm
  code/game/machinery/kitchen/gibber.dm
  code/game/machinery/recharger.dm
  code/game/objects/items.dm
  code/game/objects/items/animal_parts.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
  code/game/objects/items/weapons/tools/knifes_daggers.dm
  code/game/objects/random/oddities.dm
  code/game/objects/structures/crates_lockers/closets/secure/fontaine.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/client/preference_setup/loadout/lists/factionfontaine.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/client/preference_setup/loadout/lists/factionservice.dm
  code/modules/client/preference_setup/loadout/lists/factionskylight.dm
  code/modules/client/preference_setup/loadout/lists/factiounion.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/suits/fontaine.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/pants.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/materials/material_sheets.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/guns/energy/misc/floragun.dm
  code/modules/projectiles/guns/launcher/crossbow.dm
  code/modules/projectiles/guns/projectile/other/bow.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/reagents/reagent_containers/food/snacks/advanced_food.dm
  icons/inventory/on_suit/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/obj/animal_parts.dmi
  icons/obj/guns/projectile/liberty.dmi
  liberty-station.dme
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Bug-Fix, Documentation, Enhancement, Balance

#458 event setup
  maps/_LLEvent_maps/event_maps.dm
  maps/_LLEvent_maps/map/_event_map_engi.dmm
Labels: Test Merged

#457 Progresive spriting updates
  code/datums/craft/recipes/guild.dm
  code/game/objects/random/cloth.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/suits/armor.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Balance, Sprite Work

#460 shooty event
  icons/mob/mobs-humanoid.dmi
  liberty-station.dme
  maps/_LLEvent_maps/event_maps.dm
  maps/_LLEvent_maps/map/_event_map_bridge.dmm
  maps/__Liberty/data/shuttles-liberty.dm
Labels: Enhancement
