Repository Liberty-Landing/Liberty-Station-13, pull requests merged in 2023-10, with the labels that each got.

#493 Fontaine Armors, Corrects Decs, and Adds New Materials
  code/__DEFINES/materials.dm
  code/datums/craft/recipes/lodge.dm
  code/datums/outfits/jobs/prospector.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/suits/fontaine.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/materials.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/cult/cultist.dm
  code/modules/mob/living/carbon/superior_animal/liberty/FreeportMobs.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/corrupted_beings.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
  code/modules/mob/living/simple_animal/hostile/big.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/obj/stack/material.dmi
Labels: Balance, Content, Sprite Work

#499 mapping 1
  maps/__Liberty/area/_Liberty_areas.dm
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Balance, Map

#506 less mobs
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/maint_loot.dm
Labels: Enhancement, Balance

#508 a few of tweaks
  code/datums/datum_hud.dm
  code/modules/clothing/head/jobs.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Bug-Fix

#509 update!!
  code/game/objects/items/weapons/storage/deferred.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/mob/light_overlays.dmi
  icons/mob/rig_back.dmi
  icons/obj/rig_modules.dmi
  icons/obj/storage/deferred.dmi
Labels: Balance, Sprite Work

#507 general work
  code/datums/craft/recipes/guild.dm
  code/game/objects/items/weapons/autolathe_disk/guild_disks.dm
  code/game/objects/items/weapons/tools/mods/armor_mods.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/tool_upgrades.dmi
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Balance, Map

#511 updates
  code/datums/craft/recipes/guild.dm
  icons/inventory/uniform/icon.dmi
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Bug-Fix

#512 More Tallborgs
  code/modules/mob/living/silicon/Cyborg_AI/custom_cyborg.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/robot_upgrades.dm
  icons/mob/robot_tall/engi.dmi
  icons/mob/robot_tall/janitor.dmi
  icons/mob/robot_tall/medical.dmi
  icons/mob/robot_tall/mining.dmi
  icons/mob/robot_tall/misc.dmi
  icons/mob/robot_tall/science.dmi
  icons/mob/robot_tall/sec.dmi
  icons/mob/robot_tall/server.dmi
  icons/mob/robots.dmi
Labels: Sprite Work

#513 temp disable
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Removal

#514 updates in mining tunnels
  maps/__DeepTunnels/map/_Liberty_Deep_Tunnels.dmm
Labels: Balance, Map

#515 maint rework
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Balance, Map

#516 Ghost shells
  code/__DEFINES/perks.dm
  code/datums/perks/oddity.dm
  code/modules/projectiles/guns/_projectile.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
  code/modules/projectiles/guns/projectile/shotgun/handmade.dm
  code/modules/projectiles/guns/projectile/shotgun/pump.dm
  icons/effects/perks.dmi
Labels: Balance, Sprite Work

#517 sprite and accidental code work
  code/datums/craft/recipes/guild.dm
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/items/weapons/tools/mods/armor_mods.dm
  code/game/objects/structures/signs-faction.dm
  code/game/objects/structures/signs-misc.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/suits/greatcoat.dm
  code/modules/clothing/under/casual.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/obj/decals-faction.dmi
  icons/obj/decals-misc.dmi
  icons/obj/tool_upgrades.dmi
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Balance, Map, Sprite Work

#520 sprite and code fix
  code/datums/craft/recipes/guild.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/clothing/spacesuits/void/station.dm
  icons/inventory/head/icon.dmi
  icons/inventory/suit/icon.dmi
  maps/__DeepTunnels/map/_Liberty_Deep_Tunnels.dmm
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Balance, Map, Sprite Work

#519 frozen crashsite rework
  maps/_DeepForest/map/frozen_crashsite.dmm
Labels: Balance, Map

#522 kraft
  code/datums/craft/step.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/suits/storage.dm
Labels: Bug-Fix

#523 wall update
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Balance, Map

#524 fixes
  code/datums/outfits/equipment/backpacks.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/modular_computers/computers/subtypes/dev_wristbound.dm
  icons/inventory/hands/mob.dmi
  icons/inventory/head/mob.dmi
  icons/obj/storage/backpack.dmi
Labels: Bug-Fix, Balance, Sprite Work
