Repository Liberty-Landing/Liberty-Station-13, pull requests merged in 2023-07, with the labels that each got.

#462 misc bug fixes and slight changes
  code/__DEFINES/perks.dm
  code/controllers/subsystems/economy.dm
  code/datums/perks/backgrounds.dm
  code/datums/setup_option/backgrounds/path/path.dm
  code/game/jobs/department.dm
  code/game/jobs/job/job.dm
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/structures/turf_spawner.dm
  code/modules/core_implant/cruciform/machinery/eotp.dm
  code/modules/modular_computers/file_system/reports/crew_record.dm
Labels: Bug-Fix, Enhancement

#461 changes in terra
  code/datums/craft/recipes/guild.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/mining/mine_items.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
Labels: Balance

#464 Event Mobs
  code/modules/mob/living/carbon/superior_animal/liberty/FreeportMobs.dm
  code/modules/mob/living/carbon/superior_animal/vox/thrown_items.dm
  icons/mob/mobs-monster.dmi
  liberty-station.dme
Labels: Enhancement, Balance, Content, Sprite Work

#465 Fixes for Event
  code/modules/mob/living/carbon/superior_animal/liberty/FreeportMobs.dm
Labels: Bug-Fix

#466 TGS DMAPI 6.4.5 Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/v5/__interop_version.dm
  code/modules/tgs/v5/_defines.dm
Labels: BYOND

#467 Joke gone wrong
  code/__DEFINES/maths.dm
  code/__DEFINES/perks.dm
  code/datums/mob_stats.dm
  code/datums/perks/backgrounds.dm
  code/datums/setup_option/backgrounds/thoughts/thoughts.dm
  code/game/machinery/gym.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/traps.dm
  code/modules/clothing/head/helmet.dm
  code/modules/mob/mob.dm
  icons/effects/perks.dmi
  icons/obj/machines/gym.dmi
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Balance, Content, Sprite Work

#468 exploit fix
  code/game/objects/items/oddities_faction.dm
Labels: Bug-Fix

#470 herbacultiter
  code/modules/core_implant/cruciform/machinery/spicebed.dm
  icons/obj/neotheology_spicebed.dmi
  liberty-station.dme
Labels: Enhancement, Balance, Content, Sprite Work

#471 Updates Server Description
  code/game/world.dm
Labels: BYOND

#472 Event Sprites & Hivemind Replacements
  code/modules/core_implant/cruciform/machinery/spicebed.dm
  code/modules/hivemind/mobs.dm
  code/modules/hivemind/self_defense.dm
  code/modules/hivemind/wires.dm
  icons/mob/hivemind.dmi
  icons/mob/mobs-monster.dmi
Labels: Sprite Work

#473 Soil craft time reduction
  code/datums/craft/recipes/furniture.dm
Labels: Balance

#475 fixes some nulling
  code/datums/craft/step.dm
  code/game/objects/effects/decals/crayon.dm
  modular_liberty/cardgame_2/cardgame_2.dm
Labels: Bug-Fix
