Repository Liberty-Landing/Liberty-Station-13, pull requests merged in 2023-08, with the labels that each got.

#481 erp uniform
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
Labels: Balance

#474 I made'd the sprites porple
  icons/obj/stock_parts.dmi
Labels: Sprite Work

#478 long range buckshot
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance

#480 connections
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Map

#483 Secret club....(50 scrips the ticket!)
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Map

#482 bug hives
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Map

#487 fixes
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance
