Repository Liberty-Landing/Liberty-Station-13, pull requests merged in 2023-04, with the labels that each got.

#17 Lobby screen + Shitbirds
  code/datums/lobbyscreen.dm
  code/modules/mob/living/carbon/superior_animal/vox/types/vox_types.dm
  code/modules/mob/living/carbon/superior_animal/vox/types/wasp.dm
  code/modules/mob/living/carbon/superior_animal/vox/vox.dm
  icons/mob/mobs-voxy.dmi
  icons/title_screens/ironhammer.png
  icons/title_screens/liberty_final.png
  icons/title_screens/neotheology.png
  icons/title_screens/onestar.png
  icons/title_screens/ship.png
  icons/title_screens/transit.png
Labels: Content, Sprite Work

#14 allows snowing
  code/game/gamemodes/events/weather.dm
  code/game/gamemodes/events/weather/snow_storm.dm
  liberty-station.dme
  modular_liberty/area_blurbs.dm
Labels: Balance, Content

#20 Snowtrees and snowrocks sprites for mappers
  code/game/objects/structures/flora/snowrocks.dm
  code/game/objects/structures/flora/tree/flora_snowtree.dm
  icons/obj/flora/snowrocks.dmi
  icons/obj/flora/snowtree.dmi
  liberty-station.dme
Labels: Sprite Work

#27 snow tiles
  code/game/turfs/flooring/flooring_premade.dm
  code/modules/mining/mine_turfs.dm
  icons/turf/flooring/grass.dmi
  icons/turf/flooring/snows.dmi
Labels: Sprite Work

#23 wilsons pr and tails
  code/datums/craft/recipes/storage.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/sprite_accessories/_accessory_tail.dm
  icons/mob/sprite_accessory/tails.dmi
  icons/obj/hydroponics_machines.dmi
Labels: Balance, Port, Sprite Work

#24 vendor research data var
  code/game/machinery/vending.dm
Labels: Content

#15 ivan tweak and rnd point collection
  code/datums/helper_datums/construction_datum.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_construction/ivan.dm
  code/modules/genetics/machinery/genetics_analyzer.dm
  code/modules/research/experiment.dm
Labels: Bug-Fix, Balance

#31 rng day/night
  code/controllers/subsystems/lighting.dm
  code/game/area/Space Station 13 areas.dm
  code/game/area/areas.dm
  code/game/objects/structures/omnius.dm
  code/modules/lighting/lighting_setup.dm
Labels: Enhancement, Content

#29 Fixes decon prayer stacking
  code/modules/core_implant/cruciform/rituals/construction.dm
Labels: Bug-Fix

#32 renames hydro to themeral
  code/modules/power/hydroelectric.dm
  maps/__Liberty/map/Underground_Old.dmm
  maps/__Liberty/map/_Liberty_Colony_New.dmm
  maps/__Liberty/map/_Liberty_Colony_Omni_STU.dmm
  maps/__Liberty/map/_Liberty_Colony_Underground.dmm
Labels: Documentation, Balance

#30 Engineering Omnitool PR
  code/datums/craft/recipes/guild.dm
  code/game/objects/items/weapons/tools/misc.dm
  icons/obj/tools.dmi
Labels: Balance

#37 Colonists remember robots are made of robot
  code/_onclick/cyborg.dm
  code/game/machinery/ai_slipper.dm
  code/game/machinery/alarm.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/objs.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/syndicate.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/power/apc.dm
Labels: Balance

#34 Borgeration
  code/_onclick/cyborg.dm
  code/game/machinery/ai_slipper.dm
  code/game/machinery/alarm.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/objs.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/syndicate.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/power/apc.dm
Labels: Documentation, Enhancement, Balance

#33 new Terra Therma voidsuit drip
  code/modules/clothing/spacesuits/void/station.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Bug-Fix, Sprite Work

#26 the XGM/ZAS/airSS stuff from eris
  code/ZAS/Airflow.dm
  code/ZAS/Atom.dm
  code/ZAS/Connection.dm
  code/ZAS/ConnectionGroup.dm
  code/ZAS/ConnectionManager.dm
  code/ZAS/Controller.dm
  code/ZAS/Diagnostic.dm
  code/ZAS/Fire.dm
  code/ZAS/Plasma.dm
  code/ZAS/Turf.dm
  code/ZAS/Variable Settings.dm
  code/ZAS/Zone.dm
  code/__DEFINES/ZAS.dm
  code/__DEFINES/misc.dm
  code/controllers/subsystems/air.dm
  code/controllers/subsystems/processing/airflow.dm
  code/modules/xgm/xgm_gas_data.dm
  code/modules/xgm/xgm_gas_mixture.dm
  liberty-station.dme
Labels: Enhancement, Test Merged, Port

#39 Space
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/random/mob/misc.dm
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  code/modules/dungeons/junk_tractor_beam.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/balkan/balkan.dm
  icons/mob/mobs-humanoid.dmi
  icons/obj/vending.dmi
  liberty-station.dme
  maps/__Liberty/map/_Liberty_Colony_New.dmm
  maps/submaps/junk_field/j25_25/ironhammer/ironhammer.dm
  maps/submaps/junk_field/j25_25/military/military.dm
  maps/submaps/junk_field/j25_25/military/military1.dmm
  maps/submaps/junk_field/j25_25/military/military2.dmm
  maps/submaps/junk_field/j25_25/military/military3.dmm
  maps/submaps/junk_field/j25_25/pirate/pirate.dm
  maps/submaps/junk_field/j25_25/pirate/pirate1.dmm
  maps/submaps/junk_field/j25_25/pirate/pirate2.dmm
  maps/submaps/junk_field/j25_25/pirate/pirate3.dmm
  maps/submaps/junk_field/j25_25/serbian/serbian.dm
  maps/submaps/junk_field/j5_5/military/military.dm
  maps/submaps/junk_field/j5_5/military/military1.dmm
  maps/submaps/junk_field/j5_5/military/military2.dmm
  maps/submaps/junk_field/j5_5/military/military3.dmm
  maps/submaps/junk_field/j5_5/military/military4.dmm
  maps/submaps/junk_field/j5_5/military/military5.dmm
  maps/submaps/junk_field/j5_5/pirate/pirate.dm
  maps/submaps/junk_field/j5_5/pirate/pirate1.dmm
  maps/submaps/junk_field/j5_5/pirate/pirate2.dmm
  maps/submaps/junk_field/j5_5/pirate/pirate3.dmm
  maps/submaps/junk_field/j5_5/pirate/pirate4.dmm
  maps/submaps/junk_field/j5_5/pirate/pirate5.dmm
  sound/death_gasps/balkan_death.ogg
Labels: Balance, Map, Sprite Work

#5 The Lighting from Eris
  code/ZAS/Fire.dm
  code/__DEFINES/helpers.dm
  code/controllers/subsystems/lighting.dm
  code/datums/observation/opacity_set.dm
  code/modules/lighting/__lighting_docs.dm
  code/modules/lighting/lighting_area.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/lighting/lighting_corner.dm
  code/modules/lighting/lighting_overlay.dm
  code/modules/lighting/lighting_setup.dm
  code/modules/lighting/lighting_source.dm
  code/modules/lighting/lighting_turf.dm
  code/modules/lighting/~lighting_undefs.dm
  liberty-station.dme
Labels: Enhancement, Port, Merge Conflict

#41 Fail steps inlined with new internal organ damage
  code/modules/surgery/mods.dm
  code/modules/surgery/organic.dm
  code/modules/surgery/organic_damage.dm
  code/modules/surgery/robotic.dm
  code/modules/surgery/robotic_damage.dm
  code/modules/surgery/wound_repair.dm
Labels: Bug-Fix, Balance

#47 Fixes Gun Recoil, Wield Delay, & Descs
  code/modules/projectiles/guns/projectile/automatic/ak47.dm
  code/modules/projectiles/guns/projectile/automatic/ar.dm
  code/modules/projectiles/guns/projectile/automatic/broz.dm
  code/modules/projectiles/guns/projectile/automatic/duty.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/nationale.dm
  code/modules/projectiles/guns/projectile/automatic/operator.dm
  code/modules/projectiles/guns/projectile/automatic/slaught_o_matic.dm
  code/modules/projectiles/guns/projectile/automatic/specialist.dm
  code/modules/projectiles/guns/projectile/automatic/tactical.dm
  code/modules/projectiles/guns/projectile/automatic/umbani.dm
  code/modules/projectiles/guns/projectile/revolver/breaker.dm
  code/modules/projectiles/guns/projectile/revolver/detective.dm
  code/modules/projectiles/guns/projectile/revolver/frontier.dm
  code/modules/projectiles/guns/projectile/revolver/longrev.dm
Labels: Bug-Fix, Balance

#48 sorting and new map
  code/game/objects/structures/flora/tree/flora_snowtree.dm
  code/game/objects/structures/low_wall.dm
  code/modules/projectiles/guns/projectile/boltgun/game.dm
  icons/mob/mobs-humanoid.dmi
  icons/mob/mobs-voxy.dmi
  maps/Unused/Surface_Old.dmm
  maps/Unused/Underground_Old.dmm
  maps/Unused/_Beast_Cave.dmm
  maps/Unused/_Deep_Forest.dmm
  maps/Unused/_Hunting_Lodge.dmm
  maps/Unused/_Hunting_Lodge_guidesu.dmm
  maps/Unused/_Hunting_Lodge_old.dmm
  maps/Unused/_Liberty_Colony_Omni_STU.dmm
  maps/Unused/_Liberty_Colony_Surface.dmm
  maps/Unused/_Liberty_Colony_Transition.dmm
  maps/Unused/_Liberty_Colony_Underground.dmm
  maps/Unused/_Liberty_Colony_labercamp.dmm
  maps/Unused/_Prepper_Bunker.dmm
  maps/Unused/_River_Forest.dmm
  maps/Unused/_River_Forest_old.dmm
  maps/Unused/_River_To_Colony.dmm
  maps/Unused/_River_To_Swamp_old.dmm
  maps/Unused/_Similacrum_Field_Office.dmm
  maps/Unused/_Similacrum_Field_Office_old.dmm
  maps/_DeepForest/deepforest.dm
  maps/_DeepForest/map/frozen_forest.dmm
  maps/_HunterLodge/lodge.dm
  maps/__Liberty/area/_Liberty_areas.dm
  maps/__Liberty/liberty.dm
Labels: Bug-Fix, Balance, Map

#55 HRP email
  code/modules/multiz/map_data.dm
Labels: Bug-Fix

#54 Names
  code/__HELPERS/text.dm
  code/__HELPERS/unsorted.dm
Labels: Documentation

#51 adds sprite for union shotgun
  icons/obj/guns/energy/railshotgun.dmi
Labels: Sprite Work

#57 Church
  code/__DEFINES/jobs.dm
  code/__HELPERS/manifest.dm
  code/datums/outfits/jobs/church.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_chmant.dm
  code/datums/setup_option/backgrounds/example.dm
  code/datums/setup_option/core_implants.dm
  code/game/jobs/department.dm
  code/game/jobs/job/church.dm
  code/game/jobs/jobs.dm
  code/game/objects/landmarks/join.dm
  code/modules/client/preference_setup/loadout/lists/armament.dm
  code/modules/client/preference_setup/loadout/lists/belt.dm
  code/modules/core_implant/cruciform/machinery/eotp.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/multiz/map_data.dm
  code/modules/tips_and_tricks/jobs.dm
  maps/Unused/Surface_Old.dmm
  maps/Unused/Underground_Old.dmm
  maps/Unused/_Liberty_Colony_Omni_STU.dmm
  maps/Unused/_Liberty_Colony_Surface.dmm
  maps/Unused/_Liberty_Colony_Underground.dmm
  maps/__Liberty/map/_Liberty_Colony_New.dmm
Labels: Documentation, Enhancement

#56 Folken and Mycus and Exalt delete
  code/__DEFINES/mob_species_forms.dm
  code/__DEFINES/perks.dm
  code/datums/perks/racial.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_folken.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_human.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_mycus.dm
  code/datums/setup_option/backgrounds/habit/habit.dm
  code/datums/setup_option/backgrounds/origin.dm
  code/datums/setup_option/backgrounds/thoughts/thoughts.dm
  code/datums/setup_option/core_implants.dm
  code/game/objects/items/devices/organ_module/active/hud_types.dm
  code/modules/clothing/glasses/shades.dm
  code/modules/mob/language/outsider.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/forms/station.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/superior_animal/fungi/types/mushroom.dm
  code/modules/mob/living/carbon/superior_animal/fungi/types/slime.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/external/subtypes/exalt.dm
  code/modules/organs/internal/blood_vessels.dm
  code/modules/organs/internal/heart.dm
  code/modules/organs/internal/internal_organ_processes.dm
  code/modules/organs/internal/kidneys.dm
  code/modules/organs/internal/liver.dm
  code/modules/organs/internal/lungs.dm
  code/modules/organs/internal/muscles.dm
  code/modules/organs/internal/nerves.dm
  code/modules/organs/internal/stomach.dm
  code/modules/organs/organ_description.dm
  code/modules/sprite_accessories/_accessory_facial.dm
  code/modules/sprite_accessories/_accessory_hair.dm
  liberty-station.dme
Labels: Removal

#50 Terra Therma Changes
  code/datums/craft/recipes/guild.dm
  code/game/objects/items/weapons/autolathe_disk/guild_disks.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/random/tool_mods.dm
  code/modules/projectiles/guns/projectile/revolver/old/breakaction.dm
  code/modules/research/designs/weapon.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/advtechno.dm
Labels: Removal

#58 frozen forest fixes
  maps/_DeepForest/map/frozen_forest.dmm
  maps/__Liberty/area/_Liberty_areas.dm
Labels: Bug-Fix

#60 Medfab
  code/datums/craft/recipes/capsa.dm
  code/game/machinery/autolathe/autolathe.dm
  code/game/machinery/autolathe/medfab.dm
  code/game/objects/items/stacks/medical_stacks/bruise_pack_stack.dm
  code/game/objects/items/stacks/medical_stacks/ointment_stacks.dm
  code/game/objects/items/weapons/autolathe_disk/soteria_disks.dm
  code/game/objects/items/weapons/circuitboards/machinery/research.dm
  code/game/objects/random/lathe_disks/tools.dm
  code/modules/aberrants/organs/machinery/organfridge.dm
  code/modules/materials/material_sheets.dm
  code/modules/research/designs/medical.dm
  code/modules/research/nodes/biotech.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm
  liberty-station.dme
  maps/Unused/_River_Forest.dmm
  maps/Unused/_River_Forest_old.dmm
Labels: Balance, Removal

#61 Bouncer to Fixer
  code/__DEFINES/jobs.dm
  code/game/jobs/job/service.dm
  code/game/jobs/jobs.dm
  code/modules/multiz/map_data.dm
Labels: Bug-Fix

#62 icewalls by Albert7076#7476
  code/game/turfs/simulated/wall_attacks.dm
  code/game/turfs/simulated/wall_icon.dm
  code/game/turfs/simulated/wall_types.dm
  code/game/turfs/simulated/walls.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/worm.dm
  icons/turf/wall_masks.dmi
Labels: Enhancement, Balance, Sprite Work

#35 temperature revolution and it's consequences
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/species.dm
Labels: Balance

#49 Prospector Outfits & Locker Changes
  code/datums/autolathe/clothing.dm
  code/datums/craft/recipes/clothing.dm
  code/datums/craft/recipes/lodge.dm
  code/datums/craft/recipes/robot.dm
  code/datums/outfits/jobs/prospector.dm
  code/game/jobs/access_datum.dm
  code/game/jobs/job/prospector.dm
  code/game/objects/items/animal_parts.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/fontaine.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/accessories/holster.dm
  code/modules/clothing/glasses/misc.dm
  code/modules/clothing/gloves/jobs.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/shoes/jobs.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/fontaine.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/pirs.dm
  code/modules/clothing/under/jobs/fontaine.dm
  code/modules/mob/living/carbon/superior_animal/drone/assembly/mantis.dm
  code/modules/mob/living/carbon/superior_animal/drone/assembly/sword.dm
  code/modules/mob/living/carbon/superior_animal/drone/parts/parts.dm
  code/modules/mob/living/simple_animal/hostile/huntersprey.dm
  code/modules/projectiles/guns/projectile/shotgun/old/hunter_crossbow.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/combat.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/ears/mob.dmi
  icons/inventory/eyes/icon.dmi
  icons/inventory/eyes/mob.dmi
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/obj/radio.dmi
  icons/turf/shuttlemining.dmi
  liberty-station.dme
  maps/Unused/_Hunting_Lodge.dmm
  maps/__Liberty/data/shuttles-liberty.dm
Labels: Documentation, Balance, Sprite Work

#67 alberts transition tiles
  code/game/turfs/flooring/flooring_premade.dm
  icons/turf/flooring/grass.dmi
  icons/turf/flooring/snows.dmi
Labels: Enhancement, Sprite Work

#64 Just as the Cat intended
  code/datums/autolathe/biomatter.dm
  code/datums/craft/recipes/storage.dm
  code/game/machinery/vendor/tool_vendors.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/briefcase.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/lunchbox.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/items/weapons/storage/secure.dm
  code/game/objects/items/weapons/storage/toolbox.dm
  code/game/objects/random/pouches.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
  maps/Unused/Surface_Old.dmm
  maps/Unused/_Liberty_Colony_Omni_STU.dmm
  maps/Unused/_Liberty_Colony_Surface.dmm
  maps/__Liberty/map/_Liberty_Colony_New.dmm
Labels: Balance, Removal

#72 Event rewards be like
  code/modules/research/designs/circuits.dm
  code/modules/research/nodes/biotech.dm
  code/modules/research/nodes/similacrum.dm
Labels: Balance, Removal

#68 Corrects bullets in Fontaine lockers
  code/game/objects/structures/crates_lockers/closets/secure/fontaine.dm
Labels: Bug-Fix

#73 fixes a runetime with beakers
  code/modules/reagents/reagent_containers/glass/beaker.dm
Labels: Bug-Fix

#52 craftable union weapon update/sprite changes
  code/datums/craft/recipes/guild.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  icons/obj/weapons.dmi
Labels: Balance, Content

#71 ERT
  code/datums/craft/recipes/guild.dm
  code/datums/outfits/jobs/ghostroles.dm
  code/game/machinery/vendor/tool_vendors.dm
  code/game/objects/effects/spawners/ghostroles.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/colony/colony.dm
  icons/obj/radio.dmi
Labels: Balance, Sprite Work, Removal

#66 cloning + organs changes
  code/__DEFINES/reagents.dm
  code/game/machinery/cloning.dm
  code/game/objects/items/weapons/circuitboards/machinery/cloning.dm
  liberty-station.dme
  maps/SpaceFortress/map/exc_fort.dmm
  maps/SpaceFortress/map/space_dungeons.dmm
  maps/Unused/Underground_Old.dmm
  maps/Unused/_Hunting_Lodge_guidesu.dmm
  maps/Unused/_Liberty_Colony_Omni_STU.dmm
  maps/Unused/_Liberty_Colony_Underground.dmm
  maps/__Liberty/map/_Liberty_Colony_New.dmm
Labels: Balance, Removal

#79 skinning changes
  code/game/objects/structures/crates_lockers/closets/secure/fontaine.dm
  icons/obj/weapons.dmi
Labels: Sprite Work

#77 The maint monsters are bountiful
  code/game/objects/random/mob/roach.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/benzin.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/emp.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/fatty.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/glowing.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/hunter.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/plasmaroach.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/support.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/tank.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/tazntz.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/toxic.dm
  code/modules/reagents/reagent_containers/food/snacks/burger.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/McRonalds.dm
Labels: Documentation, Balance

#78 Cells
  code/datums/autolathe/biomatter.dm
  code/datums/autolathe/cells.dm
  code/game/machinery/vendor/tool_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/power_cells.dm
  code/modules/clothing/spacesuits/rig/suits/ameridian_knight.dm
  code/modules/core_implant/cruciform/machinery/armaments.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/projectiles/guns/energy/laser/antebellum.dm
  code/modules/projectiles/guns/energy/plasma/excubitor.dm
  code/modules/research/designs/cell.dm
  code/modules/research/nodes/power.dm
  code/modules/research/nodes/similacrum.dm
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
  code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
Labels: Balance, Removal

#81 standardized refined scrap
  code/game/machinery/autolathe/fabricators.dm
  code/game/machinery/autolathe/matterforge.dm
  code/game/machinery/kitchen/petrel_maker.dm
  code/game/mecha/mecha_wreckage.dm
  code/game/objects/structures/salvageable.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/materials.dm
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/projectiles/guns/energy/projectile/railgun.dm
  code/modules/scrap/scrap.dm
  code/modules/scrap/scrap_burner.dm
  code/modules/scrap/scrap_refine.dm
  code/modules/scrap/scrap_refinery.dm
  code/modules/scrap/scrap_stacker.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/trash_refine.dm
  icons/obj/machines/petrel_maker.dmi
  maps/Unused/_River_Forest.dmm
  maps/Unused/_River_Forest_old.dmm
  maps/Unused/_River_To_Colony.dmm
  maps/Unused/_River_To_Swamp_old.dmm
Labels: Bug-Fix, Enhancement

#82 Research
  code/__DEFINES/research.dm
  code/datums/craft/recipes/robot.dm
  code/game/mecha/mecha.dm
  code/modules/clothing/spacesuits/rig/rig_verbs.dm
  code/modules/clothing/spacesuits/rig/suits/ameridian_knight.dm
  code/modules/mob/living/silicon/robot/component.dm
  code/modules/research/designs/prosthesis_implants.dm
  code/modules/research/designs/rigmodules.dm
  code/modules/research/nodes/biotech.dm
  code/modules/research/nodes/bluespace.dm
  code/modules/research/nodes/combat.dm
  code/modules/research/nodes/engineering.dm
  code/modules/research/nodes/exosuit.dm
  code/modules/research/nodes/power.dm
  code/modules/research/nodes/robotics.dm
  code/modules/research/nodes/similacrum.dm
  code/modules/research/research.dm
  liberty-station.dme
  nano/css/shared.css
Labels: Enhancement, Balance, Removal

#84 port_gen refactor + WHOOPS
  code/__DEFINES/maths.dm
  code/game/machinery/excelsior/diesel.dm
  code/modules/materials/material_sheets.dm
  code/modules/power/diesel_gen.dm
  code/modules/power/port_gen.dm
  code/modules/power/turbine.dm
  liberty-station.dme
Labels: Bug-Fix, Documentation, Enhancement, Balance

#74 Language Rework Outline
  code/__DEFINES/chemistry.dm
  code/__DEFINES/species_languages.dm
  code/datums/perks/backgrounds.dm
  code/game/antagonist/outer/mercenary/mercenary.dm
  code/game/jobs/job/church.dm
  code/modules/admin/bluespacetech.dm
  code/modules/goonchat/browserassets/css/browserOutput_override.css
  code/modules/mob/language/outsider.dm
  code/modules/mob/language/rolion.dm
  code/modules/mob/language/romana.dm
  code/modules/mob/language/sign.dm
  code/modules/mob/language/station.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/admin_only_modules.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/paperwork/paper.dm
  code/stylesheet.dm
  liberty-station.dme
Labels: Enhancement, Balance, Removal

#88 this is just a fix for my last pr
  code/modules/power/port_gen.dm
Labels: Bug-Fix

#86 more dungeon work
  code/modules/dungeons/procedural/jp_dungeon_gen.dm
  code/modules/dungeons/procedural/precursor.dm
  code/modules/maps/tg/map_template.dm
  maps/_dungeons/deepmaint/deepmaint.dm
  maps/_dungeons/precursor/precursor.dmm
  maps/submaps/map_clearers/map_clearers.dm
  maps/submaps/map_clearers/pruins_icewall_reset.dmm
  maps/submaps/precursor_rooms/end/end_rooms.dm
  maps/submaps/precursor_rooms/end/pruin_end1.dmm
  maps/submaps/precursor_rooms/starter/starter1.dmm
  maps/submaps/precursor_rooms/starter/starter2.dmm
  maps/submaps/precursor_rooms/starter/starter3.dmm
  maps/submaps/precursor_rooms/starter/starter_rooms.dm
Labels: Bug-Fix, Enhancement, Balance, Content

#91 decl-izes snow
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_premade.dm
  icons/turf/flooring/snows.dmi
  maps/_DeepForest/map/frozen_forest.dmm
  maps/submaps/precursor_rooms/end/pruin_end1.dmm
  maps/submaps/precursor_rooms/starter/starter1.dmm
Labels: Enhancement

#94 wish things could just work 😔
  code/controllers/subsystems/staverbs.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/sound.dm
  code/modules/multiz/ztravel/climb.dm
  code/modules/power/port_gen.dm
  code/modules/reagents/machinery/grinder.dm
  sound/machines/sound_machines_generator_generator_mid2.ogg
  tgui/packages/tgui/interfaces/PortableGenerator.js
Labels: Bug-Fix

#93 Gun Name Corrections
  code/modules/core_implant/cruciform/machinery/armaments.dm
  code/modules/projectiles/guns/energy/laser/sniperrifle.dm
  code/modules/projectiles/guns/oddity_items.dm
Labels: Bug-Fix

#89 Fontaine clothes adjustments
  code/datums/outfits/jobs/prospector.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/fontaine.dm
Labels: Bug-Fix, Sprite Work

#96 Female clothing hotfix
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Bug-Fix

#97 Fixes PIRS labcoat spritepaths
  code/modules/clothing/suits/pirs.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Bug-Fix

#98 Janitor, Steward, Premier
  code/__DEFINES/jobs.dm
  code/__DEFINES/perks.dm
  code/controllers/subsystems/jobs.dm
  code/datums/datacore.dm
  code/datums/outfits/jobs/engineering.dm
  code/datums/outfits/jobs/service.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_chmant.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_human.dm
  code/datums/setup_option/core_implants.dm
  code/game/gamemodes/storyteller_helpers.dm
  code/game/jobs/access_datum.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/service.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/client/preference_setup/loadout/lists/armament.dm
  code/modules/client/preference_setup/loadout/lists/factioncommand.dm
  code/modules/client/preference_setup/loadout/lists/factionlonestar.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/multiz/map_data.dm
  code/modules/tips_and_tricks/jobs.dm
  maps/Unused/Underground_Old.dmm
  maps/Unused/_Liberty_Colony_Omni_STU.dmm
  maps/Unused/_Liberty_Colony_Underground.dmm
  maps/__Liberty/map/_Liberty_Colony_New.dmm
  tgui/public/tgui.bundle.js
Labels: Documentation, Removal

#85 Silk and biomatter
  code/__DEFINES/materials.dm
  code/datums/autolathe/biomatter.dm
  code/game/machinery/autolathe/matterforge.dm
  code/game/machinery/bioprinter_nt.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/structures/diamond_gem.dm
  code/game/turfs/simulated/wall_types.dm
  code/modules/biomatter_manipulation/biogenerator.dm
  code/modules/biomatter_manipulation/bioreactor/biotank.dm
  code/modules/biomatter_manipulation/bioreactor/platform.dm
  code/modules/biomatter_manipulation/solidifier.dm
  code/modules/biomatter_manipulation/toxic_biomass.dm
  code/modules/core_implant/cruciform/machinery/textials.dm
  code/modules/core_implant/cruciform/rituals/construction.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/materials.dm
  code/modules/organs/internal/carrion.dm
  code/modules/projectiles/guns/minigun.dm
  code/modules/projectiles/guns/oddity_items.dm
  icons/obj/machines/autolathe.dmi
  icons/obj/stack/material.dmi
  liberty-station.dme
  maps/submaps/precursor_rooms/end/pruin_end1.dmm
Labels: Enhancement, Balance, Content, Sprite Work

#101 Fixes and un-RNGs tree shadows.
  code/game/objects/structures/flora/tree/flora_snowtree.dm
  icons/obj/flora/snowtree.dmi
Labels: Bug-Fix

#102 Custodians-defaultoutfits
  code/datums/outfits/jobs/church.dm
  code/modules/clothing/suits/custodians.dm
  code/modules/clothing/under/suits.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/modules.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/mob/human_races/cyberlimbs/neotheology.dmi
  icons/obj/device.dmi
  liberty-station.dme
Labels: Documentation, Enhancement, Content, Sprite Work

#103 Lobby
  code/datums/lobbyscreen.dm
  icons/title_screens/liberty_blondie.png
  icons/title_screens/liberty_terra.png
  sound/music/lobby/clowndance.ogg
Labels: Sprite Work

#95 NEV Port - Consciousness Backup Implant
  code/__DEFINES/components.dm
  code/__DEFINES/consciousness_backup.dm
  code/datums/setup_option/core_implant.dm
  code/datums/setup_option/core_implants.dm
  code/game/jobs/access.dm
  code/game/machinery/vendor/medical_vendors.dm
  code/game/objects/items/weapons/implant/implant.dm
  code/game/objects/items/weapons/implant/implants/death_alarm.dm
  code/modules/client/preference_setup/general/02_body.dm
  code/modules/conciousness_backup/_overwrites.dm
  code/modules/conciousness_backup/access_update_tool.dm
  code/modules/conciousness_backup/base_implant.dm
  code/modules/conciousness_backup/debug.dm
  code/modules/conciousness_backup/helpers.dm
  code/modules/conciousness_backup/holochip.dm
  code/modules/conciousness_backup/module.dm
  code/modules/conciousness_backup/modules/crew_monitor.dm
  code/modules/conciousness_backup/modules/engineering.dm
  code/modules/conciousness_backup/modules/illegal.dm
  code/modules/conciousness_backup/modules/prosthetic_diag.dm
  code/modules/conciousness_backup/statpanel.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/core_implant/printer_machine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/superior_animal/drone/types/roomba.dm
  code/modules/mob/new_player/new_player.dm
  icons/obj/conback.dmi
  icons/obj/neotheology_machinery.dmi
  liberty-station.dme
Labels: Documentation, Enhancement, Sprite Work

#99 changes defibs to be less strong
  code/game/objects/items/devices/defib.dm
  code/modules/surgery/wound_repair.dm
Labels: Balance

#104 TTnSSdefaultoutfits
  code/datums/outfits/jobs/engineering.dm
  code/datums/outfits/jobs/service.dm
  code/game/jobs/job/service.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/suits.dm
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Content, Sprite Work

#63 Map Implimentation
  code/game/gamemodes/events/weather/snow_storm.dm
  code/game/jobs/job/engineering.dm
  code/game/turfs/flooring/flooring_decals.dm
  maps/_DeepForest/map/frozen_forest.dmm
  maps/__Liberty/area/_Liberty_areas.dm
  maps/__Liberty/data/_Liberty_Turbolifts.dm
  maps/__Liberty/liberty.dm
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Map

#69 Adds wild medicinal flora
  code/game/objects/random/flora.dm
  code/game/objects/structures/flora/flora_wild.dm
  code/modules/reagents/reagent_containers/food/wildflora.dm
  icons/obj/flora/medicinalflora.dmi
  icons/obj/food.dmi
  liberty-station.dme
Labels: Enhancement, Balance, Content, Sprite Work

#116 Fix Union Omnitool recipe
  code/datums/craft/recipes/guild.dm
Labels: Bug-Fix

#108 Hit messages
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
Labels: Port

#112 more armor mod stats (all "bad")
  code/datums/craft/recipes/guild.dm
  code/game/objects/items/weapons/tools/mods/_defines.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/game/objects/items/weapons/tools/mods/armor_mods.dm
Labels: Enhancement, Balance, Content

#117 Premier > Secretary
  code/controllers/subsystems/ticker.dm
  code/datums/contract.dm
  code/datums/objective/steal.dm
  code/datums/outfits/jobs/command.dm
  code/game/gamemodes/events/ion_storm.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/jobs.dm
  code/game/objects/effects/spawners/corpsespawner.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/cargo/packs_clothing.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/accessories/holster.dm
  code/modules/clothing/cloak/hooded.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/spacesuits/captain.dm
  code/modules/clothing/suits/greatcoat.dm
  code/modules/clothing/under/casual.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/paperwork/stamps.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/stashes/stash_types/captain.dm
  code/modules/tips_and_tricks/jobs.dm
  icons/obj/radio.dmi
  maps/Unused/_Liberty_Colony_Omni_STU.dmm
  maps/Unused/_Liberty_Colony_Underground.dmm
  maps/__Liberty/area/_Liberty_areas.dm
  maps/__Liberty/data/reports.dm
  maps/__Liberty/map/_Liberty_Colony.dmm
  maps/__Liberty/map/_Liberty_Colony_New.dmm
Labels: Documentation, Removal

#118 Removes Kit Vendor; Replaces with Boxes
  code/__DEFINES/jobs.dm
  code/datums/craft/recipes/guild.dm
  code/datums/outfits/jobs/security.dm
  code/game/jobs/job/security.dm
  code/game/jobs/jobs.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/multiz/map_data.dm
  code/modules/projectiles/guns/projectile/automatic/kraut.dm
  code/modules/projectiles/guns/projectile/matter_guns/matter_pistol.dm
  code/modules/projectiles/guns/projectile/pistol/liberty.dm
  icons/obj/guns/projectile/colt.dmi
  icons/obj/guns/projectile/liberty.dmi
  icons/obj/guns/projectile/luty.dmi
  icons/obj/guns/projectile/old/liberty.dmi
  icons/obj/guns/projectile/stinger.dmi
  icons/obj/guns/projectile/widowmaker.dmi
  icons/obj/guns/projectile/wristbreaker.dmi
  liberty-station.dme
  maps/__Liberty/map/_Liberty_Colony.dmm
  maps/__Liberty/map/_Liberty_Colony_New.dmm
Labels: Documentation, Enhancement, Balance, Sprite Work, Removal

#124 small fix
  code/game/objects/items/weapons/storage/hardcases.dm
Labels: Bug-Fix

#126 fixes esquimal goggles sprite path
  icons/inventory/eyes/icon.dmi
  icons/inventory/eyes/mob.dmi
Labels: Bug-Fix, Sprite Work

#130 backpack fix
  code/game/objects/items/weapons/storage/backpack.dm
  code/modules/power/solar.dm
Labels: Bug-Fix

#132 Fontaine string fixes
  code/__DEFINES/machinery.dm
  code/controllers/communications.dm
  code/datums/perks/job.dm
  code/game/jobs/job/prospector.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/weapons/autolathe_disk/lonestar_disks.dm
  code/game/objects/items/weapons/grenades/spawnergrenade.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/storage/vendor_loot_boxes.dm
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/structures/noticeboard.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/suits/storage.dm
  code/modules/flufftext/Dreaming.dm
  code/modules/mob/living/carbon/superior_animal/robots/subtype/similacrum/types/friendly.dm
  code/modules/mob/living/say.dm
  code/modules/paperwork/stamps.dm
  code/modules/projectiles/guns/projectile/shotgun/old/hunter_crossbow.dm
  maps/__Liberty/area/_Liberty_areas.dm
Labels: Bug-Fix, Documentation

#133 Deletes magnet
  code/game/machinery/magnet.dm
  liberty-station.dme
Labels: Port, Removal

#135 adds forgotten vox death sprites
  icons/mob/mobs-voxy.dmi
Labels: Bug-Fix

#109 Female underwear fixes, CAPSA poncho, green tiles replacing cyan
  code/datums/craft/recipes/floor.dm
  code/datums/underwear/bottom.dm
  code/datums/underwear/socks.dm
  code/datums/underwear/undershirt.dm
  code/game/objects/items/oddities_faction.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/structures/signs-faction.dm
  code/game/objects/structures/signs-medical.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/modules/client/preference_setup/loadout/lists/factioncapsa.dm
  code/modules/clothing/accessories/accessory.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/underwear/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/decals-faction.dmi
  icons/obj/decals-medical.dmi
  icons/obj/stack/tile.dmi
  icons/obj/storage.dmi
  icons/turf/flooring/tiles_dark.dmi
  icons/turf/flooring/tiles_steel.dmi
  icons/turf/flooring/tiles_white.dmi
  maps/SpaceFortress/map/spacefortress.dmm
  maps/Unused/Surface_Old.dmm
  maps/Unused/Underground_Old.dmm
  maps/Unused/_Liberty_Colony_Omni_STU.dmm
  maps/Unused/_Liberty_Colony_Surface.dmm
  maps/Unused/_Liberty_Colony_Transition.dmm
  maps/Unused/_Liberty_Colony_Underground.dmm
  maps/Unused/_River_To_Swamp_old.dmm
  maps/__Liberty/map/_Liberty_Colony.dmm
  maps/__Liberty/map/_Liberty_Colony_New.dmm
Labels: Sprite Work, Removal

#136 greatly explains and improves maints
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Enhancement, Map

#127 Jannie and Miner
  code/datums/outfits/jobs/engineering.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/clothing/shoes/jobs.dm
  code/modules/mining/mine_items.dm
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Balance, Map

#129 Background bugfix
  code/__DEFINES/mob_species_forms.dm
  code/datums/perks/backgrounds.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_human.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_synthetic.dm
  code/datums/setup_option/backgrounds/habit/habit.dm
  code/datums/setup_option/backgrounds/habit/habit_synthetic.dm
  code/datums/setup_option/backgrounds/thoughts/thoughts.dm
  code/datums/setup_option/backgrounds/thoughts/thoughts_synthetic.dm
  code/modules/sanity/sanity_mob.dm
Labels: Bug-Fix, Balance

#134 slimes are slightly transparent
  code/modules/mob/living/carbon/human/human.dm
Labels: Enhancement

#139 Bay's canisters
  icons/obj/atmos.dmi
Labels: Port, Sprite Work

#138 fixes erroneous paths
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
Labels: Bug-Fix

#137 Icon fixes for guns and some clothing
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/accessories/badges.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/armor.dm
  code/modules/projectiles/guns/energy/projectile/railgun.dm
  code/modules/projectiles/guns/oddity_items.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/revolver/old/capgun.dm
  icons/inventory/accessory/mob.dmi
  icons/obj/crafts.dmi
  icons/obj/guns/projectile/gatvolver.dmi
  icons/obj/guns/projectile/rahki.dmi
  icons/obj/guns/projectile/sawnoff/ar.dmi
  icons/obj/guns/projectile/slaught_o_matic.dmi
Labels: Bug-Fix, Sprite Work, Removal

#141 makes the last part of maints looks like maints
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Map

#142 fixed
  icons/obj/atmos.dmi
Labels: Sprite Work

#140 icewater
  code/game/sound.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_decals.dm
  code/game/turfs/flooring/flooring_premade.dm
  icons/inventory/uniform/mob.dmi
  icons/turf/flooring/icewater.dmi
  maps/__Liberty/Map_Liberty.dm
  sound/effects/footstep/ice1.ogg
  sound/effects/footstep/ice2.ogg
  sound/effects/footstep/ice3.ogg
  sound/effects/footstep/ice4.ogg
  sound/effects/footstep/ice5.ogg
Labels: Enhancement, Sprite Work

#144 Re-Adds Anti-Ghost w/ Changes
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/alien/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/say.dm
Labels: Enhancement

#145 minor map fixes + atmos prep
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Bug-Fix, Map

#146 misc fixes
  code/controllers/subsystems/lighting.dm
  code/controllers/subsystems/ticker.dm
  code/datums/craft/item.dm
  code/game/gamemodes/events/hivemind_invasion.dm
  code/game/objects/items/weapons/tools/misc.dm
  code/game/objects/random/mob/roach.dm
  code/game/objects/structures/omnius.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/lighting/lighting_setup.dm
  code/modules/lighting/lighting_turf.dm
  code/modules/projectiles/guns/projectile/automatic/kraut.dm
  maps/_DeepForest/map/frozen_forest.dmm
  maps/__Liberty/area/_Liberty_areas.dm
  maps/__Liberty/data/_Liberty_Turbolifts.dm
  maps/__Liberty/map/_Liberty_Colony.dmm
  maps/__Liberty/map/_Liberty_Solar_Area.dmm
  sound/misc/endshift.ogg
Labels: Bug-Fix, Enhancement, Balance

#148 radio channel colors and names
  code/controllers/communications.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/weapons/implant/implants/death_alarm.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/browserOutput_override.css
  code/modules/goonchat/browserassets/css/browserOutput_white.css
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/stylesheet.dm
  nano/templates/radio_basic.tmpl
Labels: Documentation, Enhancement

#147 medicinal flora and a few things
  code/game/objects/structures/flora/tree/flora_snowtree.dm
  maps/_DeepForest/map/frozen_forest.dmm
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Bug-Fix, Enhancement, Sprite Work

#92 Updates snow footstep sound
  code/game/sound.dm
  code/game/turfs/flooring/flooring.dm
  sound/effects/footstep/snow1.ogg
  sound/effects/footstep/snow2.ogg
  sound/effects/footstep/snow3.ogg
  sound/effects/footstep/snow4.ogg
Labels: Enhancement

#150 the rest of the radio changes
  code/controllers/communications.dm
  code/game/gamemodes/events/prison_break.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/weapons/implant/implants/death_alarm.dm
  code/modules/ameridian/ameridian_analyzer.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/power/antimatter/control.dm
  code/modules/power/hydroelectric.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/research/experiment.dm
Labels: Bug-Fix

#151 makes the outside look better
  maps/_DeepForest/map/frozen_forest.dmm
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Balance, Map

#155 atmos room redo + wiring fixes
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Map

#154 Cook
  code/modules/cooking_with_jane/cooking.dm
  code/modules/cooking_with_jane/food_overrides.dm
  code/modules/cooking_with_jane/recipes/_read_me.dm
  code/modules/cooking_with_jane/recipes/recipe.dm
  code/modules/cooking_with_jane/recipes/recipe_bread.dm
  code/modules/cooking_with_jane/recipes/recipe_burger.dm
  code/modules/cooking_with_jane/recipes/recipe_cake.dm
  code/modules/cooking_with_jane/recipes/recipe_donuts.dm
  code/modules/cooking_with_jane/recipes/recipe_egg.dm
  code/modules/cooking_with_jane/recipes/recipe_meat.dm
  code/modules/cooking_with_jane/recipes/recipe_pasta.dm
  code/modules/cooking_with_jane/recipes/recipe_pie.dm
  code/modules/cooking_with_jane/recipes/recipe_pizza.dm
  code/modules/cooking_with_jane/recipes/recipe_potato.dm
  code/modules/cooking_with_jane/recipes/recipe_salad.dm
  code/modules/cooking_with_jane/recipes/recipe_soup.dm
  code/modules/cooking_with_jane/recipes/recipe_sweets.dm
  code/modules/cooking_with_jane/recipes/recipe_unsorted.dm
  code/modules/cooking_with_jane/recipes/recipes_to_covert.dm
  code/modules/cooking_with_jane/step_defines.dm
  code/modules/cooking_with_jane/step_types/add_item.dm
  code/modules/cooking_with_jane/step_types/add_produce.dm
  code/modules/cooking_with_jane/step_types/add_reagent.dm
  code/modules/cooking_with_jane/step_types/use_grill.dm
  code/modules/cooking_with_jane/step_types/use_item.dm
  code/modules/cooking_with_jane/step_types/use_oven.dm
  code/modules/cooking_with_jane/step_types/use_stove.dm
  code/modules/cooking_with_jane/step_types/use_tool.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks/burger.dm
  code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm
  liberty-station.dme
Labels: Documentation, Balance, Removal

#152 Plasma Torch
  code/datums/outfits/jobs/science.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/projectiles/guns/energy/plasma/variant.dm
  code/modules/projectiles/guns/energy/plasma/welder.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/combat.dm
  liberty-station.dme
Labels: Balance, Removal

#164 Map Update
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Map

#163 adds in new floors for mapping
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_decals.dm
  code/game/turfs/flooring/flooring_premade.dm
  icons/obj/stack/tile.dmi
  icons/turf/flooring/decals.dmi
  icons/turf/flooring/tiles_industeral.dmi
Labels: Port, Sprite Work

#161 Maybe fixes slime digestion
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Bug-Fix

#160 Balances background selection
  code/__DEFINES/perks.dm
  code/datums/perks/backgrounds.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_human.dm
  code/datums/setup_option/backgrounds/habit/habit.dm
  code/datums/setup_option/backgrounds/path/path.dm
  code/datums/setup_option/backgrounds/thoughts/thoughts.dm
  icons/effects/perks.dmi
Labels: Balance

#158 Libertymed v4.5 fixes
  code/__DEFINES/chemistry.dm
  code/__DEFINES/tools_and_qualities.dm
  code/datums/perks/job.dm
  code/game/machinery/autodoc.dm
  code/game/machinery/vendor/medical_vendors.dm
  code/game/objects/items/stacks/medical_stacks/bruise_pack_stack.dm
  code/game/objects/items/stacks/medical_stacks/ointment_stacks.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/misc.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/items/weapons/tools/tape.dm
  code/modules/aberrants/organs/_defines.dm
  code/modules/aberrants/organs/machinery/organ_fabricator.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/mob/living/carbon/slime/slime.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/organs/internal/borer.dm
  code/modules/organs/internal/internal_wounds/bone.dm
  code/modules/organs/internal/internal_wounds/organic.dm
  code/modules/psionics/psion_powers/gear_summoning_powers.dm
  code/modules/psionics/psionic_items/psi_temp_items.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/reagent_containers/food/snacks/advanced_food.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/reagents/reagent_containers/food/snacks/sandwich.dm
  code/modules/reagents/reagent_containers/food/snacks/soup.dm
  code/modules/reagents/reagent_containers/food/snacks/vendor_food.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/reagents/stims.dm
  code/modules/reagents/recipes/recipes.dm
  code/modules/research/xenoarchaeology/machinery/geosample_scanner.dm
  code/modules/surgery/organic_damage.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
  code/modules/virus2/effect.dm
  icons/obj/syringe.dmi
  modular_liberty/Borers/__ADMIN SHIT/organs.dm
  modular_liberty/Borers/borer.dm
Labels: Bug-Fix, Documentation, Enhancement, Balance, Sprite Work, Removal

#157 Moldmaxxing
  code/game/objects/random/booze.dm
  code/game/objects/random/food.dm
  code/game/objects/random/purerandom.dm
  code/game/objects/random/scrap.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/scrap/scrap.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/trash_refine.dm
  liberty-station.dme
  maps/Unused/Surface_Old.dmm
  maps/Unused/_Beast_Cave.dmm
  maps/Unused/_Deep_Forest.dmm
  maps/Unused/_Liberty_Colony_Omni_STU.dmm
  maps/Unused/_Liberty_Colony_Surface.dmm
  maps/Unused/_Prepper_Bunker.dmm
  maps/Unused/_River_Forest.dmm
  maps/Unused/_River_Forest_old.dmm
  maps/Unused/_Similacrum_Field_Office.dmm
  maps/Unused/_Similacrum_Field_Office_old.dmm
  maps/_DeepForest/map/frozen_forest.dmm
  maps/__Liberty/map/_Liberty_Colony.dmm
  maps/__Liberty/map/_Liberty_Colony_New.dmm
  maps/submaps/deepmaint_rooms/core/diner.dmm
Labels: Balance, Removal

#165 small ports
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/modules/mob/living/silicon/robot/gripper.dm
Labels: Port

#159 Agape_GunCircuits_Logos_HotFixes
  code/modules/integrated_electronics/core/assemblies.dm
  code/modules/mob/living/simple_animal/hostile/big.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  icons/inventory/uniform/mob.dmi
  icons/mob/64x64.dmi
  icons/mob/agape.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/ss13_32.png
  icons/ss13_64.png
Labels: Bug-Fix, Balance, Sprite Work

#166 more map fixes and wall stuff
  code/game/turfs/flooring/flooring_premade.dm
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Bug-Fix, Balance, Map

#156 Biogen and Medfab
  code/game/machinery/autolathe/medfab.dm
  code/game/machinery/biogenerator.dm
  code/game/objects/items/weapons/autolathe_disk/soteria_disks.dm
  code/modules/research/designs/medical.dm
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Balance, Removal

#169 Fixes mining
  code/modules/mining/mine_items.dm
  maps/__DeepTunnels/map/_Liberty_Deep_Tunnels.dmm
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Bug-Fix, Map

#168 Janitor back to Skylight with DROMKII DRIP
  code/datums/outfits/jobs/engineering.dm
  code/datums/outfits/jobs/service.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/service.dm
  code/modules/clothing/shoes/jobs.dm
  code/modules/clothing/under/suits.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/uniform/Skylight_clothes.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Balance, Sprite Work

#167 Sugar Honey Glucose
  code/__DEFINES/perks.dm
  code/datums/setup_option/backgrounds/habit/habit.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/food-Drinks.dm
Labels: Balance, Removal

#172 disables some bad things and adds more stats bags
  code/datums/setup_option/core_implants.dm
  code/game/machinery/cryo.dm
  code/game/objects/items/devices/defib.dm
  code/game/objects/structures/crates_lockers/closets/secure/fontaine.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/mob/living/silicon/robot/gripper.dm
  code/modules/organs/internal/psionic.dm
  code/modules/psionics/psion_powers/teleporation_powers.dm
Labels: Enhancement, Balance

#170 Vendors
  code/game/machinery/vendor/cloathing.dm
  code/game/machinery/vendor/food_vendors.dm
  code/game/machinery/vendor/integrated_electronics.dm
  code/game/machinery/vendor/labtop_vendor.dm
  code/game/machinery/vendor/medical_vendors.dm
  code/game/machinery/vendor/misc_vendors.dm
  code/game/machinery/vendor/one_star_vending.dm
  code/game/machinery/vendor/technologies.dm
  code/game/machinery/vendor/tool_vendors.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  code/modules/reagents/reagent_containers/syringes.dm
  icons/obj/vending.dmi
  maps/SpaceFortress/map/space_dungeons.dmm
  maps/Unused/Underground_Old.dmm
  maps/Unused/_Deep_Forest.dmm
  maps/Unused/_Liberty_Colony_Omni_STU.dmm
  maps/Unused/_Liberty_Colony_Transition.dmm
  maps/Unused/_Liberty_Colony_Underground.dmm
  maps/Unused/_Prepper_Bunker.dmm
  maps/__Liberty/map/_Liberty_Colony.dmm
  maps/__Liberty/map/_Liberty_Colony_New.dmm
Labels: Balance, Map, Removal

#176 fixes runtime in port_gen.dm
  code/modules/power/port_gen.dm
Labels: Bug-Fix
