Repository Liberty-Landing/Liberty-Station-13, pull requests merged in 2023-03, with the labels that each got.

#1 The voting changes
  code/controllers/subsystems/ticker.dm
  code/controllers/subsystems/vote.dm
  code/controllers/subsystems/voting/poll_types.dm
Labels: Balance

#8 borg syringe fix
  code/game/machinery/kitchen/smartfridge.dm
Labels: Bug-Fix

#10 renames synths
  code/__DEFINES/mob_species_forms.dm
  code/datums/setup_option/backgrounds/origin_homeworld.dm
  code/datums/setup_option/backgrounds/origin_synthetic.dm
  code/datums/setup_option/backgrounds/origin_upbringing.dm
  code/datums/setup_option/core_implants.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/offcolony.dm
  code/game/jobs/job/prospector.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/modules/mob/living/carbon/human/species/forms/station.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/organs/organ_description.dm
  code/modules/sprite_accessories/_accessory_hair.dm
Labels: Documentation

#7 psionic harvester use fix
  code/modules/research/xenoarchaeology/machinery/psionic_harvester.dm
Labels: Bug-Fix

#12 Perk Icons
  code/datums/perks/backgrounds.dm
  code/datums/perks/cooldown.dm
  code/datums/perks/imprinter_perks.dm
  code/datums/perks/job.dm
  code/datums/perks/nanogate.dm
  code/datums/perks/nepotism.dm
  code/datums/perks/oddity.dm
  code/datums/perks/perk.dm
  code/datums/perks/psionic.dm
  code/datums/perks/racial.dm
  icons/effects/perks.dmi
Labels: Enhancement, Sprite Work

#11 Cool map tools
  code/game/machinery/atmoalter/scrubber.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/game/turfs/unsimulated/floor.dm
  code/game/turfs/unsimulated/walls.dm
Labels: Documentation, Enhancement, Content

#13 frost handling
  code/game/objects/structures/watercloset.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_frost.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/organs/external/subtypes/standard.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/food-Drinks.dm
  liberty-station.dme
Labels: Balance, Content

#9 Perk perkinson
  code/datums/perks/racial.dm
  code/datums/setup_option/backgrounds/origin_career.dm
  code/datums/setup_option/backgrounds/origin_kriosan.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/reagents/reagents/race.dm
Labels: Balance

#6 Harry, you forgot your stats!
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/turfs/flooring/flooring.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/Ploge.dm
  code/modules/mob/living/carbon/superior_animal/xenomorph/types/XenoRobust.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/sanity/sanity_mob.dm
Labels: Balance
