Repository Liberty-Landing/Liberty-Station-13, pull requests merged in 2023-09, with the labels that each got.

#486 Neew dorms
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Enhancement, Balance, Map

#491 addition1
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
Labels: Bug-Fix

#490 fixes
  code/modules/clothing/spacesuits/void/station.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/head/mob.dmi.orig
Labels: Bug-Fix

#492 additions
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Enhancement, Balance, Map

#494 nerfs
  code/game/objects/items/weapons/tools/simple_weapons.dm
Labels: Balance

#489 Games Map
  maps/_LLEvent_maps/event_maps.dm
  maps/_LLEvent_maps/map/_event_games.dmm
Labels: Map

#496 Map Touchups
  code/__DEFINES/machinery.dm
  code/game/gamemodes/events/weather/rad_storm.dm
  code/game/machinery/camera/presets.dm
  code/game/machinery/flasher.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/random/structures.dm
  code/game/objects/structures/crates_lockers/closets/walllocker.dm
  code/game/objects/structures/mirror.dm
  code/game/objects/structures/window_spawner.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/modular_computers/file_system/programs/generic/camera.dm
  code/modules/power/os_port_gen.dm
  icons/obj/structures.dmi
  icons/obj/watercloset.dmi
  icons/turf/areas.dmi
  icons/turf/flooring/decals.dmi
  maps/Unused/Underground_Old.dmm
  maps/Unused/_Liberty_Colony_Omni_STU.dmm
  maps/Unused/_Liberty_Colony_Surface.dmm
  maps/Unused/_Liberty_Colony_Underground.dmm
  maps/_DeepForest/map/frozen_crashsite.dmm
  maps/_DeepForest/map/frozen_forest.dmm
  maps/__Liberty/area/_Liberty_areas.dm
  maps/__Liberty/map/_Liberty_Colony.dmm
  maps/__Liberty/map/_Liberty_Colony_New.dmm
Labels: Bug-Fix, Balance, Map

#498 spawners 1
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Map

#497 [COMMISSION] Slime transparency and Markings removal
  code/__DEFINES/mob_species_forms.dm
  code/modules/client/preference_setup/general/06_furry.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/sprite_accessories/_accessory_facial.dm
  code/modules/sprite_accessories/_accessory_hair.dm
Labels: Enhancement, Content

#495 balances in character creation
  code/datums/setup_option/backgrounds/ancestry/ancestry_human.dm
  code/datums/setup_option/backgrounds/path/path.dm
  code/datums/setup_option/backgrounds/thoughts/thoughts.dm
Labels: Balance

#488 additions
  code/game/machinery/excelsior/ex_turret.dm
  code/game/machinery/portable_turret.dm
  icons/obj/machines/excelsior/turret.dmi
Labels: Bug-Fix, Enhancement, Balance

#502 sprite update
  icons/mob/mobs-humanoid.dmi
Labels: Sprite Work

#500 tweaks toolimplant multy
  code/datums/craft/recipes/tools.dm
  code/game/objects/items/devices/organ_module/active/multitool/makeshift_multy.dm
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Balance

#503 new hud sytle
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/datums/datum_hud.dm
  code/modules/client/ui_style.dm
  code/modules/mob/living/carbon/human/human_hud.dm
  code/modules/mob/living/carbon/human/species/species_hud.dm
  code/modules/mob/living/silicon/robot/robot_hud.dm
  icons/mob/screen/LibertyStyle.dmi
Labels: Enhancement, Balance, Sprite Work

#501 Custodian Balenciaga 2.0 Edition
  code/__DEFINES/misc.dm
  code/__DEFINES/tools_and_qualities.dm
  code/datums/setup_option/core_implants.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/molds.dm
  code/game/objects/structures/burrows.dm
  code/modules/client/preference_setup/loadout/lists/factionbonfire.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/suits.dm
  code/modules/core_implant/core_implant.dm
  code/modules/core_implant/hearthcore/hearthcore.dm
  code/modules/core_implant/hearthcore/lantern.dm
  code/modules/core_implant/hearthcore/lectures/custodian.dm
  code/modules/core_implant/hearthcore/lectures/jobs.dm
  code/modules/dungeons/junk_tractor_beam.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/obj/burrows.dmi
  icons/obj/candle.dmi
  icons/obj/neural_link.dmi
Labels: Enhancement, Balance, Sprite Work, Removal

#505 Fix HUD overlap on style change
  code/modules/client/ui_style.dm
  code/modules/mob/living/carbon/human/human_hud.dm
  code/modules/mob/living/living_hud.dm
Labels: Bug-Fix

#504 better_stomic icons
  icons/mob/screen/LibertyStyle.dmi
Labels: Sprite Work
