Repository Liberty-Landing/Liberty-Station-13, pull requests merged in 2023-05, with the labels that each got.

#179 fixes briefcases on loadout
  code/modules/client/preference_setup/loadout/lists/utility.dm
Labels: Bug-Fix

#183 Lift fix
  code/game/machinery/os_portable_turret.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
  code/modules/organs/internal/slime.dm
  icons/obj/flora/snowrocks.dmi
  icons/obj/guns/projectile/stinger.dmi
  icons/obj/stack/items.dmi
  maps/_DeepForest/map/frozen_forest.dmm
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Bug-Fix, Balance, Map

#182 precursor temp disable
  maps/_dungeons/precursor/precursor.dm
Labels: Removal

#181 Gives acess_merchant to Club Manager
  code/game/jobs/job/service.dm
Labels: Balance

#173 Ports #8093
  code/game/machinery/smelter.dm
Labels: Port

#184 miner adjustments
  code/datums/outfits/jobs/engineering.dm
  code/game/jobs/job/engineering.dm
Labels: Bug-Fix, Balance

#186 Paper Worm
  code/__DEFINES/perks.dm
  code/datums/perks/backgrounds.dm
  code/datums/setup_option/backgrounds/habit/habit.dm
Labels: Balance, Removal

#188 fix a burger
  code/modules/reagents/reagent_containers/food/snacks/burger.dm
Labels: Bug-Fix

#190 forgot an else
  code/modules/mob/living/carbon/human/human.dm
Labels: Bug-Fix

#191 Recipe galore
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/cooking_with_jane/recipes/recipe_bread.dm
  code/modules/cooking_with_jane/recipes/recipe_burger.dm
  code/modules/cooking_with_jane/recipes/recipe_cake.dm
  code/modules/cooking_with_jane/recipes/recipes_microwave.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/benzin.dm
  code/modules/reagents/reagent_containers/food/cubes.dm
  code/modules/reagents/reagent_containers/food/snacks/burger.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  liberty-station.dme
Labels: Bug-Fix, Enhancement

#192 service job fix
  code/game/jobs/job/service.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
Labels: Bug-Fix, Enhancement, Balance

#194 Blackshieldus Deletus
  code/datums/craft/recipes/storage.dm
  code/datums/outfits/jobs/ghostroles.dm
  code/datums/outfits/jobs/security.dm
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/game/machinery/vendor/misc_vendors.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/weapons/stock_parts.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/items/weapons/tools/knifes_daggers.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/game/objects/items/weapons/vouchers.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/game/objects/structures/noticeboard.dm
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/accessories/armband.dm
  code/modules/clothing/accessories/badges.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/jobs/militia.dm
  code/modules/mining/abandonedcrates.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/colony/colony.dm
  code/modules/mob/living/simple_animal/hostile/huntersprey.dm
  code/modules/organs/external/subtypes/robotic_types.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/cybernetics.dm
  liberty-station.dme
  maps/Unused/_Liberty_Colony_Omni_STU.dmm
  maps/__Liberty/map/_Liberty_Colony.dmm
  maps/__Liberty/map/_Liberty_Colony_New.dmm
Labels: Removal

#196 rusted walls an floors
  code/game/objects/structures/low_wall.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/game/turfs/simulated/wall_types.dm
  icons/obj/structures/low_wall.dmi
  icons/turf/flooring/rusted.dmi
  icons/turf/flooring/rusted2.dmi
  icons/turf/wall_masks.dmi
Labels: Sprite Work

#199 Terra guns
  code/modules/projectiles/guns/projectile/matter_guns/matter_pistol.dm
Labels: Balance

#200 changes in-game year
  code/__HELPERS/time.dm
  code/global.dm
  code/modules/games/spaceball_cards.dm
Labels: Bug-Fix

#201 Union boss job description
  code/game/jobs/job/engineering.dm
Labels: Documentation

#195 Changes le funny song to less le funny song ):
  code/datums/lobbyscreen.dm
Labels: Bug-Fix

#189 Cargo tug no longer lags the player when approaching
  code/modules/vehicles/cargo_train.dm
  code/modules/vehicles/train.dm
Labels: Enhancement

#198 Tail Fix/Ear addition
  code/modules/sprite_accessories/_accessory_ears.dm
  icons/mob/sprite_accessory/ears.dmi
  icons/mob/sprite_accessory/tails.dmi
Labels: Sprite Work

#206 disposals fixes
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Map

#208 chapel stair fix
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Map

#205 boulder tweaks
  code/game/objects/structures/flora/snowrocks.dm
Labels: Bug-Fix

#203 this time to end it
  code/game/jobs/job/engineering.dm
Labels: Bug-Fix, Documentation

#209 fixes implants not spawning
  code/modules/mob/living/carbon/human/human.dm
Labels: Bug-Fix

#213 Report Templates
  maps/__Liberty/data/reports.dm
Labels: Bug-Fix, Documentation

#212 Adds button to open Mech Bay
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Map

#197 Service
  code/__DEFINES/jobs.dm
  code/__DEFINES/perks.dm
  code/datums/perks/job.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/service.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/multiz/map_data.dm
Labels: Bug-Fix, Balance

#216 Makes a vendor non generic
  code/game/machinery/vendor/food_vendors.dm
  code/game/machinery/vendor/tool_vendors.dm
  icons/obj/vending.dmi
Labels: Bug-Fix, Documentation

#214 Offer burger names
  code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm
  code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm
Labels: Documentation

#193 Loadouts
  code/datums/craft/recipes/weapon.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/modules/client/preference_setup/loadout/lists/armament.dm
  code/modules/client/preference_setup/loadout/lists/belt.dm
  code/modules/client/preference_setup/loadout/lists/clothing.dm
  code/modules/client/preference_setup/loadout/lists/cosmetics.dm
  code/modules/client/preference_setup/loadout/lists/earwear.dm
  code/modules/client/preference_setup/loadout/lists/eyegear.dm
  code/modules/client/preference_setup/loadout/lists/general.dm
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/client/preference_setup/loadout/lists/tools.dm
  code/modules/client/preference_setup/loadout/lists/utility.dm
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
  code/modules/clothing/accessories/holster.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/projectiles/guns/projectile/pistol/clarissa.dm
  liberty-station.dme
Labels: Documentation, Enhancement, Balance, Removal

#217 too many map changes
  code/modules/genetics/creatures/golden_roach.dm
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Bug-Fix, Map

#218 Update Board Secretary Description
  code/game/jobs/job/captain.dm
Labels: Documentation, Balance

#220 Revert "Borgeration"
  code/_onclick/cyborg.dm
  code/game/machinery/ai_slipper.dm
  code/game/machinery/alarm.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/objs.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/syndicate.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/power/apc.dm
Labels: Balance

#223 fixes loadout guns
  code/modules/client/preference_setup/loadout/lists/armament.dm
Labels: Bug-Fix

#224 Fixes R&D oversight
  code/modules/research/nodes/combat.dm
  code/modules/research/nodes/illegal.dm
Labels: Bug-Fix

#225 Hardsuit moment
  code/modules/clothing/spacesuits/rig/modules/ninja.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
Labels: Bug-Fix

#226 Hardware Imprinter
  code/__DEFINES/perks.dm
  code/datums/autolathe/devices.dm
  code/datums/perks/imprinter_perks.dm
  code/game/objects/items/devices/hardware_imprinter.dm
  code/modules/mob/living/carbon/human/human_recoil.dm
  code/modules/mob/living/living_recoil.dm
  code/modules/research/designs/devices.dm
  code/modules/research/nodes/engineering.dm
  code/modules/trade/datums/trade_stations_presets/4-unique/illegalbeacon1.dm
  liberty-station.dme
Labels: Removal

#227 new heater sprites
  icons/obj/atmos.dmi
Labels: Sprite Work

#231 Shuttle names
  code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm
  code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
  code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm
  code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
Labels: Documentation

#230 Removes Solfed References
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/random/oddities.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/accessories/accessory.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/storage.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/solgov/marines.dm
  code/modules/modular_computers/file_system/programs/generic/coin_miner.dm
  code/modules/projectiles/guns/projectile/automatic/old/battlerifle.dm
  code/modules/projectiles/guns/projectile/automatic/old/chaingun.dm
  code/modules/projectiles/guns/projectile/pistol/old/ladon.dm
  code/modules/projectiles/guns/projectile/pistol/old/lamia.dm
  code/modules/reagents/reagent_containers/food/cans.dm
  code/modules/reagents/reagent_containers/glass/beaker.dm
  code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
Labels: Documentation

#228 long story, short pr
  code/modules/power/generator.dm
  tgui/packages/tgui/interfaces/TEGenerator.js
Labels: Enhancement

#215 Department Dosh and Wages
  code/game/jobs/department.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/service.dm
Labels: Balance

#234 custodian strings and materials
  code/datums/autolathe/biomatter.dm
  code/game/gamemodes/scores.dm
  code/game/machinery/vendor/weapon_vendors.dm
  code/game/objects/items/oddities_faction.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/autolathe_disk/bonfire_disks.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/storage.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/structures/noticeboard.dm
  code/modules/core_implant/cruciform/bible.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/organs/external/subtypes/robotic_types.dm
Labels: Documentation

#235 atmos tweaks
  code/ATMOSPHERICS/components/unary/outlet_injector.dm
  code/game/machinery/spaceheater.dm
Labels: Balance

#238 PIRS loadout clothes
  code/modules/client/preference_setup/loadout/lists/factionphokorus.dm
Labels: Bug-Fix

#237 renames some crafting stuff, more to come
  code/datums/craft/recipes/guild.dm
Labels: Documentation

#236 Tahca Replacement, New Round End SFX, Small Fix
  code/datums/craft/recipes/lodge.dm
  code/game/objects/items/animal_parts.dm
  code/game/objects/items/stacks/medical_stacks/bruise_pack_stack.dm
  code/modules/mob/living/simple_animal/hostile/misc.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
  icons/inventory/uniform/Skylight_clothes.dmi
  icons/mob/mobs-domestic.dmi
  sound/misc/endshift.ogg
  sound/misc/endshift_kay.ogg
Labels: Balance, Content, Sprite Work

#242 map tweaks and common sense
  code/__DEFINES/perks.dm
  code/datums/perks/job.dm
  code/game/jobs/job/service.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Bug-Fix, Balance, Map

#243 CAPSA reagents
  nano/templates/chemistry_catalog.tmpl
Labels: Documentation

#241 roboto accessoh!
  code/modules/reagents/machinery/grinder.dm
Labels: Bug-Fix

#240 fixer slot counts increase
  code/game/jobs/job/service.dm
Labels: Balance

#233 Psi and Tesla
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/research/designs/weapon.dm
  code/modules/research/nodes/combat.dm
Labels: Balance

#246 Fixes Skylight Fixer & Renames Watchmen Gear
  code/datums/craft/recipes/clothing.dm
  code/datums/perks/job.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/service.dm
  code/game/objects/items/devices/holowarrant.dm
  code/game/objects/items/devices/propaganda_chip.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/autolathe_disk/gun_parts_disks.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/manuals.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/landmarks/general.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/noticeboard.dm
  code/modules/cargo/packs_clothing.dm
  code/modules/cargo/packs_security.dm
  code/modules/clothing/accessories/armband.dm
  code/modules/clothing/accessories/badges.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/flufftext/Dreaming.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiImpressive.dm
  code/modules/modular_computers/file_system/news_article.dm
  maps/__Liberty/data/_Liberty_factions.dm
Labels: Bug-Fix, Documentation, Removal

#250 Background balance AGAIN
  code/__DEFINES/perks.dm
  code/datums/perks/backgrounds.dm
  code/datums/perks/job.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_akula.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_chmant.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_cindarite.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_human.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_kriosan.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_marqua.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_naramad.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_opifex.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_sablekyne.dm
  code/datums/setup_option/backgrounds/habit/habit.dm
  code/datums/setup_option/backgrounds/habit/habit_synthetic.dm
  code/datums/setup_option/backgrounds/origin.dm
  code/datums/setup_option/backgrounds/path/path.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  liberty-station.dme
Labels: Balance, Removal

#247 Fixes a missing floor in the brig
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Bug-Fix

#251 guess git commands do not work here
  tgui/public/tgui-bench.bundle.css
  tgui/public/tgui-bench.bundle.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui-say.bundle.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: Bug-Fix, Documentation

#252 fix disposal
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Bug-Fix

#255 Tips
  code/modules/tips_and_tricks/gameplay.dm
  code/modules/tips_and_tricks/jobs.dm
  code/modules/tips_and_tricks/mobs.dm
Labels: Documentation

#256 News
  code/game/periodic_news.dm
  code/modules/modular_computers/file_system/news_article.dm
  news_articles/Agent_Captured.html
  news_articles/An_odd_twist_of_fate.html
  news_articles/Call_to_Action.html
  news_articles/CardCarp.html
  news_articles/Catastrophic_Outbreak.html
  news_articles/Deep_Maint_Psychosis.html
  news_articles/Didnt_think_to_ask_if_they_should.html
  news_articles/Emily_chu.html
  news_articles/FIRE_IN_THE_JUNGLE.html
  news_articles/Full_stop.html
  news_articles/Gatehouse_Clusterfuck.html
  news_articles/Listening_Post_Destroyed.html
  news_articles/Mangos_Untitled_Stream.html
  news_articles/Morning_Star.html
  news_articles/Official_Marshal_communique.html
  news_articles/Progress.html
  news_articles/Psionic_Ascension.html
  news_articles/Psionic_Medicine.html
  news_articles/Scrap_Haven.html
  news_articles/Sniper_Assault.html
  news_articles/The_month_in_recap.html
  news_articles/Whoever_fights_monsters.html
  news_articles/kros_news.html
  news_articles/kros_news_ii.html
  strings/artist_strings/descriptors/art_locations.txt
Labels: Documentation, Removal

#258 Skill screen
  code/modules/client/preference_setup/general/07_stats.dm
Labels: Balance

#259 Liberty Watch Armors & Sprites
  code/datums/craft/recipes/repairs.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/security_kits.dm
  code/game/objects/random/cloth.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/spacesuits/bomb.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/jobs/security.dm
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Balance, Map, Sprite Work

#262 wiring check in the mines
  maps/__DeepTunnels/map/_Liberty_Deep_Tunnels.dmm
Labels: Map

#264 prs in for work half the done outsider/new dungeon map
  maps/_DeepForest/map/frozen_crashsite.dmm
Labels: Map

#265 Fixer momemntos
  code/game/jobs/job/service.dm
Labels: Bug-Fix, Balance

#267 Gun Sprite Fixes
  code/modules/projectiles/guns/projectile/automatic/ar.dm
  icons/obj/guns/projectile/ak5.dmi
  icons/obj/guns/projectile/ar.dmi
Labels: Sprite Work

#266 New Outside Map - Take 2
  code/__DEFINES/materials.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/materials.dm
  code/modules/tables/sandbags.dm
  icons/obj/sandbags.dmi
  icons/obj/structures/barricades.dmi
  liberty-station.dme
  maps/_DeepForest/map/frozen_crashsite.dmm
  maps/__Liberty/area/_Liberty_areas.dm
Labels: Map

#268 Fixes Watch Sprites
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Bug-Fix

#269 more fixes
  icons/inventory/suit/mob_fem.dmi
  icons/obj/flora/snowrocks.dmi
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Bug-Fix

#271 pushing more tweaks to frozen crash
  maps/_DeepForest/deepforest.dm
  maps/_DeepForest/map/frozen_crashsite.dmm
Labels: Map

#277 Fixes Fixer Description
  code/game/jobs/job/service.dm
Labels: Bug-Fix

#279 Vendor Food 2.0
  code/game/machinery/vendor/misc_vendors.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/storage/lunchbox.dm
  code/game/objects/random/cigarettes.dm
  code/modules/reagents/reagent_containers/food/cans.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/snacks/advanced_food.dm
  code/modules/reagents/reagent_containers/food/snacks/vendor_food.dm
Labels: Documentation

#274 the bridge to 515
  code/__byond_version_compat.dm
  code/_compile_options.dm
  liberty-station.dme
Labels: BYOND

#261 Statter
  code/__DEFINES/mob_stats.dm
  code/__DEFINES/perks.dm
  code/controllers/subsystems/jobs.dm
  code/controllers/subsystems/staverbs.dm
  code/datums/mob_stats.dm
  code/datums/perks/backgrounds.dm
  code/datums/perks/job.dm
  code/datums/perks/oddity.dm
  code/datums/setup_option/backgrounds/path/path.dm
  code/datums/setup_option/backgrounds/thoughts/thoughts.dm
  code/game/machinery/autolathe/artist_bench.dm
  code/game/objects/items/devices/organ_module/active/armblades.dm
  code/game/objects/items/oddities_faction.dm
  code/game/objects/items/weapons/storage/perk_kits.dm
  code/modules/aberrants/organs/internal/teratoma.dm
  code/modules/client/preference_setup/general/07_stats.dm
  code/modules/core_implant/cruciform/machinery/eotp.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/psi_monster.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiRobust.dm
  code/modules/mob/living/carbon/superior_animal/psi_monsters/types/PsiTrash.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/mob.dm
  code/modules/psionics/psion.dm
  code/modules/psionics/psion_powers/gear_summoning_powers.dm
  code/modules/psionics/psion_powers/healing_powers.dm
  code/modules/psionics/psion_powers/pyschiatrist_powers.dm
  code/modules/reagents/metabolism.dm
  code/modules/sanity/breakdowns.dm
  code/modules/sanity/sanity_mob.dm
  icons/obj/storage.dmi
  liberty-station.dme
  modular_liberty/task_master/tasks.dm
Labels: Balance, Removal

#272 Removes mentions of excelsior
  code/__HELPERS/mobs.dm
  code/controllers/subsystems/ticker.dm
  code/datums/autolathe/circuits.dm
  code/datums/autolathe/clothing.dm
  code/datums/autolathe/devices.dm
  code/datums/autolathe/parts.dm
  code/datums/contract.dm
  code/game/antagonist/station/revolutionary/excel_faction.dm
  code/game/antagonist/station/revolutionary/excelsior.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/autodoc_excelsior.dm
  code/game/machinery/autolathe_disk_cloner.dm
  code/game/machinery/excelsior/autolathe.dm
  code/game/machinery/excelsior/blackshield_teleporter.dm
  code/game/machinery/excelsior/ex_bluespace_fixer.dm
  code/game/machinery/excelsior/ex_teleporter.dm
  code/game/machinery/excelsior/ex_turret.dm
  code/game/machinery/excelsior/field.dm
  code/game/machinery/excelsior/implantmaker.dm
  code/game/mecha/combat/marauder.dm
  code/game/objects/items/devices/propaganda_chip.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/RCD.dm
  code/game/objects/items/weapons/autolathe_disk/similacrum_excelsior_disks.dm
  code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/items/weapons/grenades/explosive.dm
  code/game/objects/items/weapons/implant/implanter.dm
  code/game/objects/items/weapons/implant/implants/excelsior.dm
  code/game/objects/items/weapons/mine.dm
  code/game/objects/items/weapons/stock_parts.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/structures/mines.dm
  code/game/objects/structures/signs-faction.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/spacesuits/void/excelsior.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/mob/language/codespeak.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/excelsior/excelsior.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/excelsior.dm
  code/modules/mob/living/simple_animal/hostile/huntersprey.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/laser/antebellum.dm
  code/modules/projectiles/guns/launcher.dm
  code/modules/projectiles/guns/projectile/automatic/old/drozd.dm
  code/modules/projectiles/guns/projectile/automatic/old/ppsh.dm
  code/modules/projectiles/guns/projectile/automatic/old/vintorez.dm
  code/modules/projectiles/guns/projectile/revolver/old/wayfarer.dm
  code/modules/stashes/stash_types/excelsior.dm
  liberty-station.dme
  maps/Centcom/map/centcom.dmm
  maps/SpaceFortress/map/exc_fort.dmm
  maps/SpaceFortress/map/space_dungeons.dmm
  nano/templates/excelsior_teleporter.tmpl
Labels: Documentation, Removal

#281 Precursor rooms, Device and Test Chamber
  code/game/area/Space Station 13 areas.dm
  code/modules/dungeons/procedural/precursor.dm
  code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
  maps/_dungeons/precursor/precursor.dm
  maps/_dungeons/precursor/precursor.dmm
  maps/submaps/precursor_rooms/large/anomaly_study_chambers.dmm
  maps/submaps/precursor_rooms/large/artic_vault.dmm
  maps/submaps/precursor_rooms/large/facility_rooms.dmm
  maps/submaps/precursor_rooms/large/flooded_comms.dmm
  maps/submaps/precursor_rooms/large/flooded_core.dmm
  maps/submaps/precursor_rooms/large/hedge_maze.dmm
  maps/submaps/precursor_rooms/large/holdout_fail.dmm
  maps/submaps/precursor_rooms/large/kitchen.dmm
  maps/submaps/precursor_rooms/large/large_rooms.dm
  maps/submaps/precursor_rooms/large/overgrown_library.dmm
  maps/submaps/precursor_rooms/large/rusty_labs.dmm
  maps/submaps/precursor_rooms/large/shuttles.dmm
  maps/submaps/precursor_rooms/starter/example.dmm
  maps/submaps/precursor_rooms/starter/starter1.dmm
  maps/submaps/precursor_rooms/starter/starter2.dmm
  maps/submaps/precursor_rooms/starter/starter3.dmm
  maps/submaps/precursor_rooms/template.dm
Labels: Balance, Map, Sprite Work

#282 Last needed changes for crashsight map
  code/game/turfs/simulated/wall_types.dm
  maps/Unused/_River_Forest.dmm
  maps/_DeepForest/deepforest.dm
  maps/_DeepForest/map/frozen_crashsite.dmm
  maps/_DeepForest/map/frozen_forest.dmm
  maps/__Liberty/area/_Liberty_areas.dm
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Map

#283 makes lighting work by area transitions
  maps/_DeepForest/map/frozen_crashsite.dmm
Labels: Map

#289 hopefully it's this causing the voting issues
  code/controllers/subsystems/vote.dm
Labels: Bug-Fix

#288 Endurance gaming
  code/__DEFINES/mob_stats.dm
  code/game/machinery/autolathe/artist_bench.dm
  code/game/objects/items/oddities_faction.dm
  code/modules/aberrants/organs/internal/teratoma.dm
  code/modules/core_implant/cruciform/machinery/eotp.dm
  code/modules/reagents/metabolism.dm
  code/modules/sanity/breakdowns.dm
  code/modules/sanity/sanity_mob.dm
Labels: Bug-Fix

#287 FBP/Marking fix
  code/modules/organs/body_modifications.dm
  code/modules/organs/external/subtypes/robotic_types.dm
  icons/mob/human_races/cyberlimbs/fbp.dmi
  icons/mob/human_races/markings.dmi
Labels: Bug-Fix

#280 Account Balance
  code/__DEFINES/economy.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/offcolony.dm
  code/game/jobs/job/prospector.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/service.dm
Labels: Balance

#291 makes the new types of floors have a nonbroken type
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_premade.dm
Labels: Content

#290 reduces termite cluster/swarm and hoard spawns
  code/game/objects/random/mob/golems.dm
  code/game/objects/random/mob/misc.dm
  code/game/objects/random/mob/roach.dm
  code/game/objects/random/mob/slime.dm
  code/game/objects/random/mob/spider.dm
  code/game/objects/random/mob/termite.dm
  maps/_DeepForest/map/frozen_crashsite.dmm
Labels: Documentation, Balance, Map

#296 Actually makes news work
  code/modules/economy/economy_misc.dm
  code/modules/modular_computers/file_system/news_article.dm
  news_articles/Lionel_interview.html
Labels: Bug-Fix

#297 Gun fixes 2.0
  code/modules/projectiles/guns/projectile/automatic/duty.dm
  code/modules/projectiles/guns/projectile/automatic/lmg.dm
  code/modules/projectiles/guns/projectile/automatic/nationale.dm
  code/modules/projectiles/guns/projectile/automatic/tactical.dm
Labels: Bug-Fix

#299 Fixes wallet runtime
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/client/preference_setup/loadout/lists/utility.dm
Labels: Bug-Fix

#301 that is how mafia works
  maps/__Liberty/data/_Liberty_factions.dm
Labels: Bug-Fix

#300 More gun fixes
  code/datums/craft/gun_parts.dm
  code/game/machinery/crafting_station.dm
  code/game/objects/random/guns.dm
  code/modules/projectiles/guns/energy/laser/nuclear.dm
  code/modules/projectiles/guns/projectile/pistol/martian.dm
  code/modules/projectiles/guns/projectile/revolver/handmade.dm
  code/modules/projectiles/guns/projectile/shotgun/handmade.dm
  icons/inventory/head/mob.dmi
  icons/obj/guns/projectile/marksman.dmi
  icons/obj/guns/projectile/nationale.dmi
Labels: Bug-Fix, Balance, Removal

#298 Grenades
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/grenades/emgrenade.dm
  code/game/objects/items/weapons/grenades/explosive.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/grenades/frag.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/grenades/heatwave.dm
  code/game/objects/items/weapons/grenades/smokebomb.dm
  code/game/objects/items/weapons/storage/boxes.dm
  icons/obj/grenade.dmi
Labels: Balance

#303 Fixes faulty spawn behavior
  code/game/objects/landmarks/join.dm
  maps/_DeepForest/map/frozen_crashsite.dmm
Labels: Bug-Fix

#294 Minor map bug fixes and additions.
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Map

#304 Frozen Crash Site area dynamic lighting and outdoor lights
  maps/_DeepForest/map/frozen_crashsite.dmm
  maps/__Liberty/area/_Liberty_areas.dm
Labels: Bug-Fix, Map

#306 Trash
  code/game/objects/items/trash.dm
Labels: Documentation

#307 paramedic and gamer boltgun sawn thing
  code/game/jobs/job/medical.dm
  code/modules/projectiles/guns/projectile/boltgun/game.dm
Labels: Bug-Fix, Balance

#309 Fixing Fixers
  code/game/jobs/job/service.dm
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Bug-Fix, Balance

#305 Markings and Prosthetics
  code/__DEFINES/mob_species_forms.dm
  code/modules/mob/living/carbon/human/species/forms/alien.dm
  code/modules/mob/living/carbon/human/species/forms/station.dm
  code/modules/organs/body_modifications.dm
  code/modules/organs/external/subtypes/robotic_types.dm
  code/modules/research/designs/prosthesis_implants.dm
  code/modules/sprite_accessories/_accessory_marking.dm
  code/modules/sprite_accessories/_accessory_skin.dm
  code/modules/sprite_accessories/_accessory_tail_taur.dm
  icons/mob/human_races/cyberlimbs/bishop.dmi
  icons/mob/human_races/cyberlimbs/blackshield.dmi
  icons/mob/human_races/cyberlimbs/hesphaistos.dmi
  icons/mob/human_races/cyberlimbs/hesphaistos_alt.dmi
  icons/mob/human_races/cyberlimbs/nashef-agunabi.dmi
  icons/mob/human_races/cyberlimbs/spirit.dmi
  icons/mob/human_races/cyberlimbs/ward.dmi
  icons/mob/human_races/cyberlimbs/watch.dmi
  icons/mob/human_races/cyberlimbs/xion.dmi
  icons/mob/human_races/cyberlimbs/zenghu.dmi
  icons/mob/human_races/markings.dmi
  icons/mob/human_races/r_def_plant.dmi
  icons/mob/human_races/r_def_xenochimera.dmi
  icons/mob/human_races/r_def_xenomorph.dmi
  icons/mob/human_races/r_diona.dmi
  icons/mob/human_races/r_folken.dmi
  icons/mob/human_races/r_mycus.dmi
  icons/mob/human_races/r_xenochimera.dmi
  icons/mob/human_races/r_xenomorph.dmi
  icons/mob/human_races/xenos/r_xenos_drone.dmi
  icons/mob/human_races/xenos/r_xenos_hunter.dmi
  icons/mob/human_races/xenos/r_xenos_queen.dmi
  icons/mob/human_races/xenos/r_xenos_sentinel.dmi
  icons/mob/taursuit/cow.dmi
  icons/mob/taursuit/horse.dmi
  icons/mob/taursuit/lizard.dmi
  icons/mob/taursuit/naga.dmi
  icons/mob/taursuit/wolf.dmi
  liberty-station.dme
Labels: Documentation, Balance, Removal

#311 Fixes tactical having smg 9mm
  code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
Labels: Bug-Fix

#313 Slime and Monkey(s)
  code/datums/setup_option/backgrounds/ancestry/ancestry_human.dm
  code/datums/setup_option/backgrounds/ancestry/ancestry_slime.dm
  icons/mob/human_races/monkeys/r_farwa.dmi
  icons/mob/human_races/monkeys/r_monkey.dmi
  icons/mob/human_races/monkeys/r_neaera.dmi
  icons/mob/human_races/monkeys/r_stok.dmi
  icons/mob/human_races/monkeys/r_wolpin.dmi
Labels: Bug-Fix, Balance, Content

#308 Hair
  code/modules/sprite_accessories/_accessory_hair.dm
  icons/mob/human_races/species/human/hair.dmi
Labels: Sprite Work

#295 Opifex
  code/datums/setup_option/backgrounds/thoughts/thoughts.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Balance

#219 Updates various job descriptions and duties
  code/game/jobs/job/church.dm
  code/game/jobs/job/prospector.dm
  code/game/jobs/job/science.dm
Labels: Documentation

#317 Map changes and fixes
  code/game/jobs/job/assistant.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/core_implant/printer_machine.dm
  icons/obj/machines/chemistry.dmi
  maps/__Liberty/area/_Liberty_areas.dm
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Bug-Fix, Balance, Map, Sprite Work

#319 Hair and Band-Aids...
  code/modules/sprite_accessories/_accessory_hair.dm
  code/modules/sprite_accessories/_accessory_marking.dm
  icons/mob/human_races/markings.dmi
  icons/mob/human_races/species/human/hair.dmi
Labels: Bug-Fix

#316 Disables noob names for now
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/prospector.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
Labels: Bug-Fix

#315 Style momentos
  code/modules/clothing/suits/armor.dm
Labels: Balance

#320 subtracts one
  code/datums/autolathe/guns.dm
Labels: Bug-Fix

#321 Somehow more gun fixes
  code/modules/projectiles/guns/projectile/automatic/ar.dm
  icons/obj/guns/projectile/sawnoff/trench.dmi
Labels: Bug-Fix

#322 Assistant Drip
  code/datums/outfits/jobs/civilian.dm
  code/game/objects/random/cloth.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/jobs/civilian.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Sprite Work

#323 Pixie
  code/modules/sprite_accessories/_accessory_hair.dm
  icons/mob/human_races/species/human/hair.dmi
Labels: Sprite Work

#324 Supermatter price
  code/modules/power/supermatter/supermatter.dm
Labels: Balance

#325 Sanity
  code/modules/sanity/sanity_mob.dm
  nano/templates/sanity.tmpl
Labels: Documentation, Enhancement, Balance

#326 Custodian Wages
  code/game/jobs/job/church.dm
Labels: Balance

#328 Racial Tempetures
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Balance

#327 lowers costs and fixes colt
  code/modules/research/designs/medical.dm
  icons/obj/guns/projectile/colt.dmi
Labels: Bug-Fix, Balance

#329 Reaction time
  code/modules/mob/living/carbon/superior_animal/human/subtype/balkan/balkan.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/excelsior/excelsior.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
Labels: Bug-Fix, Balance

#330 Hex
  code/game/machinery/vendor/one_star_vending.dm
  code/game/machinery/vendor/tool_vendors.dm
  icons/obj/vending.dmi
Labels: Documentation, Sprite Work

#331 9mm drum fix
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic/broz.dm
  code/modules/projectiles/guns/projectile/automatic/luty.dm
  code/modules/projectiles/guns/projectile/automatic/specialist.dm
Labels: Bug-Fix

#333 Hair.dmi hotfix
  icons/mob/human_races/species/human/hair.dmi
Labels: Bug-Fix

#334 Fixes Deputy Chief's Names and Access
  code/game/jobs/job/security.dm
  code/game/objects/items/toys.dm
  code/modules/client/preference_setup/loadout/lists/factionsecurity.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/jobs/security.dm
Labels: Bug-Fix, Balance

#335 Dinar drop fix
  code/modules/economy/coalition_dinar.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/balkan/balkan.dm
Labels: Bug-Fix

#337 Maxim fix
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  icons/obj/guns/projectile/maxim.dmi
Labels: Bug-Fix

#338 General fixes
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/random/guns.dm
  code/modules/clothing/chameleon.dm
Labels: Bug-Fix, Sprite Work, Removal

#339 switches out renders for agapes
  code/game/objects/random/mob/misc.dm
  maps/_DeepForest/map/frozen_crashsite.dmm
  maps/_DeepForest/map/frozen_forest.dmm
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Bug-Fix

#340 fixes some bad doors
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Bug-Fix

#341 Gun icon fixes
  code/modules/projectiles/guns/energy/projectile/stun.dm
  icons/obj/guns/energy/si_stunrevolver.dmi
  icons/obj/guns/energy/stunrevolver.dmi
  icons/obj/guns/energy/taser.dmi
Labels: Bug-Fix

#344 custodian decoratives
  code/game/objects/structures/custodian_decorations.dm
  icons/obj/structures/64x64_decorations.dmi
  icons/obj/structures/custodian_decorations.dmi
  liberty-station.dme
Labels: Content, Sprite Work

#343 custodian bugfixes
  code/datums/outfits/jobs/church.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/modules/reagents/reagents/toxins.dm
  icons/mob/items/righthand.dmi
Labels: Bug-Fix

#350 Restores Vox and Ameridian spawning events
  code/game/gamemodes/events/migration_ameridian.dm
  code/game/gamemodes/events/migration_vox.dm
Labels: Bug-Fix

#351 alembic sprite fix
  code/modules/reagents/machinery/alchemy.dm
Labels: Bug-Fix

#352 Custodian Crafting adjustments
  code/datums/autolathe/biomatter.dm
  code/datums/craft/recipes/custodians.dm
  code/game/objects/items/molds.dm
  code/modules/core_implant/cruciform/rituals/construction.dm
Labels: Balance

#349 Cooking with Gidgit
  code/game/machinery/vendor/food_vendors.dm
  code/game/objects/items/weapons/material/kitchen.dm
  code/modules/cooking_with_jane/cooking_catalog.dm
  code/modules/cooking_with_jane/recipes/recipe_bread.dm
  code/modules/cooking_with_jane/recipes/recipe_burger.dm
  code/modules/cooking_with_jane/recipes/recipe_cake.dm
  code/modules/cooking_with_jane/recipes/recipe_meat.dm
  code/modules/cooking_with_jane/recipes/recipe_pie.dm
  code/modules/cooking_with_jane/recipes/recipe_soup.dm
  code/modules/cooking_with_jane/recipes/recipe_sweets.dm
  code/modules/cooking_with_jane/recipes/recipe_unsorted.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/vendor_food.dm
  code/modules/reagents/recipes/recipes_food_drinks.dm
  icons/obj/food.dmi
  icons/obj/food_ingredients.dmi
  icons/obj/kitchen.dmi
Labels: Bug-Fix, Documentation, Balance

#353 vermouth station
  code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm
Labels: Bug-Fix, Balance

#356 Mercenary Bunker Area and Outdoor Lights
  maps/_DeepForest/map/frozen_crashsite.dmm
  maps/__Liberty/area/_Liberty_areas.dm
Labels: Bug-Fix, Balance, Map

#348 Custodian Bug-Fixing 2: The Crisis at San Diego
  code/game/jobs/job/church.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/tools/misc.dm
  code/game/objects/structures/custodian_decorations.dm
  code/modules/core_implant/cruciform/machinery/eotp.dm
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/core_implant/cruciform/upgrades.dm
  maps/__Liberty/map/_Liberty_Colony.dmm
  nano/templates/bioreactor.tmpl
Labels: Bug-Fix, Balance

#355 Enables mask generation on frozen crash site
  maps/_DeepForest/deepforest.dm
Labels: Enhancement, Balance

#357 Kriosan Ancestry Changes
  code/datums/setup_option/backgrounds/ancestry/ancestry_kriosan.dm
Labels: Documentation

#342 Take 2: QOL and Eris Wielding port
  code/game/objects/items/_inventory.dm
  code/game/turfs/flooring/flooring.dm
  code/modules/mob/inventory.dm
Labels: Bug-Fix, Balance, Port

#359 waaaaaaaaaaaaaaaaaaaaaah
  code/modules/organs/external/subtypes/robotic_types.dm
Labels: Bug-Fix

#361 precursor map initilization
  code/modules/dungeons/procedural/jp_dungeon_gen.dm
Labels: Bug-Fix

#358 my feelings dont care about your fcats
  code/__DEFINES/perks.dm
  code/datums/perks/cooldown.dm
  code/datums/perks/oddity.dm
  code/datums/perks/special.dm
  code/datums/setup_option/backgrounds/thoughts/thoughts.dm
  icons/effects/perks.dmi
  modular_liberty/task_master/_task_master_defines.dm
  modular_liberty/task_master/tasks.dm
Labels: Enhancement, Balance

#363 Drill mining adjustments
  code/modules/mining/drilling/drill.dm
  code/modules/mining/drilling/termite_burrow.dm
  code/modules/mining/drilling/termite_wave.dm
  maps/__DeepTunnels/map/_Liberty_Deep_Tunnels.dmm
Labels: Enhancement, Balance, Content

#365 tiny bit of custodian stuff
  code/controllers/subsystems/jobs.dm
  code/game/jobs/job/job.dm
  code/modules/clothing/suits/armor.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/custodian.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/core_implant/ritual.dm
  code/modules/library/lib_items.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/inventory/on_suit/mob.dmi
  nano/templates/ritual_book.tmpl
Labels: Bug-Fix, Enhancement, Balance, Sprite Work

#366 Custodians disks and fixes
  code/datums/autolathe/biomatter.dm
  code/game/objects/items/stacks/medical_stacks/splint_stacks.dm
  code/game/objects/items/weapons/autolathe_disk/bonfire_disks.dm
  code/game/objects/items/weapons/autolathe_disk/soteria_disks.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/modules/core_implant/cruciform/machinery/armaments.dm
  code/modules/research/designs/medical.dm
  icons/obj/discs.dmi
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Enhancement, Balance, Sprite Work

#367 Gun and sprite fix
  code/modules/economy/coalition_dinar.dm
  code/modules/projectiles/guns/projectile/revolver/ranger.dm
Labels: Bug-Fix

#362 Better mob health check
  code/modules/mob/living/carbon/superior_animal/ai.dm
Labels: Balance

#369 Fixes invisible willpower
  code/modules/client/preference_setup/general/07_stats.dm
Labels: Bug-Fix

#364 Fixes rogue drones, adjusts end event for vox and ameridian events
  code/game/gamemodes/events/migration_ameridian.dm
  code/game/gamemodes/events/migration_vox.dm
  code/game/gamemodes/events/rogue_drones.dm
Labels: Bug-Fix

#370 makes pristine animal fangs stack
  code/datums/craft/recipes/lodge.dm
  code/game/objects/items/animal_parts.dm
  code/modules/mob/living/carbon/superior_animal/vox/vox.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/big.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/creature.dm
  code/modules/mob/living/simple_animal/hostile/misc.dm
  code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
Labels: Enhancement, Balance

#372 Biosculptor Renaissance
  code/game/machinery/biosculptor.dm
Labels: Bug-Fix, Balance

#375 Bluespace leak breakdowns
  modular_liberty/spaceleak.dm
Labels: Bug-Fix
