Repository Liberty-Landing/Liberty-Station-13, pull requests merged in 2024-01, with the labels that each got.

#534 wawawaw
  code/game/objects/items/weapons/tools/hammer.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
Labels: Balance

#536 TGS DMAPI Update 7.0.1
  code/__DEFINES/tgs.dm
  code/modules/tgs/v5/__interop_version.dm
  code/modules/tgs/v5/_defines.dm
  code/modules/tgs/v5/api.dm
  code/modules/tgs/v5/bridge.dm
  code/modules/tgs/v5/topic.dm
  code/modules/tgs/v5/undefs.dm
Labels: Documentation

#537 The great wave of Development part 1
  code/game/objects/effects/decals/remains.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/trash_material.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/game/objects/random/cloth.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/suits/armor.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/effects/blood.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/obj/guns/projectile/martian.dmi
  icons/obj/material_trash.dmi
  icons/obj/storage/deferred.dmi
  maps/__Liberty/map/_Liberty_Colony.dmm
Labels: Documentation, Enhancement, Balance, Sprite Work
